type BridgeCommandType = "addBehaviour"                     |
                         "allowDimming"                     |
                         "bootloaderToNormalMode"           |
                         "cancelConnectionRequest"          |
                         "clearErrors"                      |
                         "commandFactoryReset"              |
                         "connect"                          |
                         "disconnectCommand"                |
                         "factoryResetHub"                  |
                         "factoryResetHubOnly"              |
                         "getAdcChannelSwaps"               |
                         "getAdcRestarts"                   |
                         "getBehaviour"                     |
                         "getBehaviourDebugInformation"     |
                         "getBootloaderVersion"             |
                         "getCrownstoneUptime"              |
                         "getCurrentMultiplier"             |
                         "getCurrentZero"                   |
                         "getDimmerCurrentThreshold"        |
                         "getDimmerTempDownThreshold"       |
                         "getDimmerTempUpThreshold"         |
                         "getFirmwareVersion"               |
                         "getGPREGRET"                      |
                         "getHardwareVersion"               |
                         "getLastResetReason"               |
                         "getMACAddress"                    |
                         "getMaxChipTemp"                   |
                         "getMinSchedulerFreeSpace"         |
                         "getPowerSamples"                  |
                         "getPowerZero"                     |
                         "getResetCounter"                  |
                         "getSoftOnSpeed"                   |
                         "getSwitchHistory"                 |
                         "getSwitchState"                   |
                         "getSwitchcraftThreshold"          |
                         "getTapToToggleThresholdOffset"    |
                         "getTime"                          |
                         "getVoltageMultiplier"             |
                         "getVoltageZero"                   |
                         "lockSwitch"                       |
                         "multiSwitch"                      |
                         "performDFU"                       |
                         "phoneDisconnect"                  |
                         "putInDFU"                         |
                         "recover"                          |
                         "registerTrackedDevice"            |
                         "removeBehaviour"                  |
                         "requestCloudId"                   |
                         "restartCrownstone"                |
                         "sendMeshNoOp"                     |
                         "sendNoOp"                         |
                         "setCurrentMultiplier"             |
                         "setCurrentZero"                   |
                         "setDimmerCurrentThreshold"        |
                         "setDimmerTempDownThreshold"       |
                         "setDimmerTempUpThreshold"         |
                         "setMaxChipTemp"                   |
                         "setPowerZero"                     |
                         "setSoftOnSpeed"                   |
                         "setSunTimesViaConnection"         |
                         "setSwitchCraft"                   |
                         "setSwitchcraftThreshold"          |
                         "setTapToToggle"                   |
                         "setTapToToggleThresholdOffset"    |
                         "setTime"                          |
                         "setUartKey"                       |
                         "setUartState"                     |
                         "setVoltageMultiplier"             |
                         "setVoltageZero"                   |
                         "setupCrownstone"                  |
                         "setupFactoryReset"                |
                         "setupPulse"                       |
                         "setupPutInDFU"                    |
                         "switchDimmer"                     |
                         "switchRelay"                      |
                         "syncBehaviours"                   |
                         "toggle"                           |
                         "trackedDeviceHeartbeat"           |
                         "transferHubTokenAndCloudId"       |
                         "turnOn"                           |
                         "updateBehaviour"                  |
