export default {
  ActivityLog:{
    __filename: "../js/views/overlays/WhatsNew/2.2.0/ActivityLog.tsx",
    Activity_Log_:              () => { return "Activity Log!" },
    Ever_wonder_why_a_Crownst:  () => { return "Ever wonder why a Crownstone switched? Why is it on?\n\n" + "In the new Activity Log, you can see exactly why this is!\n\n" + "You can find the new log in the Crownstone settings (by tapping on a Crownstone icon in a room) and navigating to the right.\n\n" },
  },
  ActivityLogStatusIndicator:{
    __filename: "../js/views/deviceViews/elements/activityLog/ActivityLogStatusIndicator.tsx",
    Im_in_range_:               () => { return "I'm in range!" },
  },
  AddItemsToSphere:{
    __filename: "../js/views/main/AddItemsToSphere.tsx",
    Add_to_your_Sphere:         () => { return "Add to your Sphere" },
    You_can_add_Rooms__People:  () => { return "You can add Rooms, People or Crownstones to your Sphere. As more devices will be integrated with the Crownstone, they will appear here as well!\n\nWhat do you want to add?" },
  },
  AiStart:{
    __filename: "../js/views/startupViews/AiStart.tsx",
    Welcome__:                  () => { return "Welcome " + arguments[0] + "!" },
    Im_your_house_:             () => { return "I'm your house!" },
    What_would_you_like_to_ca:  () => { return "What would you like to call me?" },
    Whats_my_gender_:           () => { return "What's my gender?" },
    OK:                         () => { return "OK" },
  },
  AnimatedDoubleTap:{
    __filename: "../js/views/components/animated/AnimatedDoubleTap.tsx",
    __x__:                      () => { return "1 x.." },
    __x_:                       () => { return "2 x!" },
  },
  ApplianceEntry:{
    __filename: "../js/views/components/ApplianceEntry.tsx",
    _current_:                  () => { return "(current)" },
  },
  AutomaticRecentering:{
    __filename: "../js/views/overlays/WhatsNew/1.10.2/AutomaticRecentering.tsx",
    If_you_scroll_too_far_in_:  () => { return "If you scroll too far in the Sphere overview, I will now recenter your view and show the double tap shortcut!" },
  },
  Awesome:{
    __filename: "../js/views/overlays/WhatsNew/Awesome.tsx",
    Thats_it_for_this_update_:  () => { return "That's it for this update!" },
    Enjoy_the_new_version_:     () => { return "Enjoy the new version!" },
    Thanks_:                    () => { return "Thanks!" },
  },
  BatteryImprovements:{
    __filename: "../js/views/overlays/WhatsNew/2.0.0/BatteryImprovements.tsx",
    Battery_Improvements_:      () => { return "Battery Improvements!" },
    The_Crownstone_app_will_n:  () => { return "The Crownstone app will now use less power in the background for the localization features! The more Crownstones you have, the more efficient it becomes!" },
  },
  BugsFixedAndroid:{
    __filename: "../js/views/overlays/WhatsNew/2.1.2/BugsFixedAndroid.tsx",
    Bug_fixes_:                 () => { return "Bug fixes." },
    __Fixed_bug_that_caused_i:  () => { return "- Fixed bug that caused indoor localization not to work.\n\n" + "- Fixed near/far triggers.\n\n" + "- Fixed switching as hub." },
  },
  BugsFixedAndroid1_10_2:{
    __filename: "../js/views/overlays/WhatsNew/1.10.2/BugsFixedAndroid1.10.2.tsx",
    Issues_that_caused_the_ap:  () => { return "Issues that caused the app to crash when the firmware update was finished are now resolved." },
    You_can_safely_update_all:  () => { return "You can safely update all Crownstones now :)" },
  },
  BugsFixediOS1_10_2:{
    __filename: "../js/views/overlays/WhatsNew/1.10.2/BugsFixediOS1.10.2.tsx",
    Many_other_issues_have_be:  () => { return "Many other issues have been addressed:" },
    __You_can_invite_members_:  () => { return "- You can invite members and guests to your Sphere without them getting errors." + "\n\n- Battery saving improved when not using localization." + "\n\n- Fixed issue where the app would show not in Sphere while being in range of your Crownstones." + "\n\n- Animated user moving from room to room, fixing user showing up in multiple rooms." },
  },
  CancelButton:{
    __filename: "../js/views/components/topbar/CancelButton.tsx",
    Cancel:                     () => { return "Cancel" },
  },
  CloudChoice:{
    __filename: "../js/views/startupViews/CloudChoice.tsx",
    PLEASE_SELECT:              () => { return "PLEASE SELECT" },
    Use_the_Cloud_to_store_da:  () => { return "Use the Cloud to store data" },
    The_cloud_is_used_to_allo:  () => { return "The cloud is used to allow multiple users to use your Crownstones. Crownstones, spheres, rooms are stored in the cloud and synces across devices." },
    Only_store_data_on_your_p:  () => { return "Only store data on your phone" },
    If_you_are_the_only_user_:  () => { return "If you are the only user, you can run everything locally. If you uninstall your app, you'll need to physically reset all your Crownstones." },
  },
  DebugIconSelection:{
    __filename: "../js/views/development/DebugIconSelection.tsx",
    _o__:                       () => { return arguments[0] + " o:" + arguments[1] + "," + arguments[2] },
  },
  DeviceActivityLog:{
    __filename: "../js/views/deviceViews/elements/DeviceActivityLog.tsx",
    Activity_Log:               () => { return "Activity Log" },
    In_this_log_you_can_see_w:  () => { return "In this log you can see why the Crownstone was switched. The newest entries are at the top. This data is stored for 24 hours." },
    If_you_do_not_share_your_:  () => { return "If you do not share your activity logs, other users in your Sphere may get an incorrect activity log." },
    Nothing_yet___:             () => { return "Nothing yet..." },
    Only_members_and_admins_c:  () => { return "Only members and admins can see the activity logs..." },
  },
  DeviceBehaviour:{
    __filename: "../js/views/deviceViews/elements/DeviceBehaviour.tsx",
    This_Crownstone_is_locked:  () => { return "This Crownstone is locked so the behaviour is disabled." },
    Behaviour_is_disabled_in_:  () => { return "Behaviour is disabled in the App Settings. Re-enable indoor localization to use the behaviour." },
    Heartbeat_is_disabled_in_:  () => { return "Heartbeat is disabled in the App Settings. Re-enable the Heartbeat to use the exit behaviour." },
    Near_away_is_disabled_unt:  () => { return "Near/away is disabled until you define where near is. Press change at the top to do this now." },
    Behaviour:                  () => { return "Behaviour" },
    This_is_how_I_respond_to_:  () => { return "This is how I respond to your location:" },
    I_will_:                    () => { return arguments[0] || "I will " },
    only_:                      () => { return "only" },
    _TURN_ON:                   () => { return "TURN ON" },
    _if_it_is_dark_outside_:    () => { return "if it is dark outside." },
    TURN_ON:                    () => { return "TURN ON" },
    TURN_OFF:                   () => { return "TURN OFF" },
    I_wont_do_anything___:      () => { return "I won't do anything..." },
  },
  DeviceEdit:{
    __filename: "../js/views/deviceViews/DeviceEdit.tsx",
    Checking_versions____:      () => { return "Checking versions... " },
    address__:                  () => { return "address: " + (arguments[0] || arguments[1]) },
    hardware_id__:              () => { return "hardware id: " + (arguments[0] || arguments[1]) },
    bootloader__:               () => { return "bootloader: " + (arguments[0] || arguments[1]) },
    firmware__:                 () => { return "firmware: " + (arguments[0] || arguments[1]) },
    crownstone_id__:            () => { return "crownstone id: " + (arguments[0] || arguments[1]) },
  },
  DeviceEntry:{
    __filename: "../js/views/components/deviceEntries/DeviceEntry.tsx",
    Tap_me_for_more_:           () => { return "Tap me for more!" },
    Sent_via_mesh_:             () => { return "Sent via mesh!" },
  },
  DeviceEntrySubText:{
    __filename: "../js/views/components/deviceEntries/DeviceEntrySubText.tsx",
    _W:                         () => { return arguments[0] + " W" },
    __Nearest_:                 () => { return " (Nearest)" },
    __Nearest_in_room_:         () => { return " (Nearest in room)" },
    __Very_near_:               () => { return " (Very near)" },
    __Near_:                    () => { return " (Near)" },
    _Nearest_:                  () => { return "(Nearest)" },
    _Very_near_:                () => { return "(Very near)" },
    _Near_:                     () => { return "(Near)" },
    Please_wait_until_the_set:  () => { return arguments[0] ? "Please wait until the setup process is complete." : "Searching..." },
  },
  DeviceError:{
    __filename: "../js/views/deviceViews/elements/DeviceError.tsx",
    Reset_Error:                () => { return "Reset Error" },
    Notify_an_admin_of_your_S:  () => { return "Notify an admin of your Sphere to resolve this error." },
    Error_Detected:             () => { return "Error Detected" },
  },
  DevicePowerCurve:{
    __filename: "../js/views/deviceViews/elements/DevicePowerCurve.tsx",
    Power_Usage:                () => { return "Power Usage" },
    Sneak_preview_of_the_dyna:  () => { return "Sneak preview of the dynamic power usage overview for this Crownstone!" },
    Stand_near_the_Crownstone:  () => { return "Stand near the Crownstone to see the measurements flowing in! It will only measure if the app is in the foreground. " + "Future versions of the app will allow you to freely scroll and zoom in and out. Scroll down on the text for more upcoming features! " + "\n\nIn the future, the power usage overview will be sorted by the Devices you use, as well as an extra view to summarize the entire usage in your Sphere, categorized by room, devices and much more!\n\n\n\n" },
  },
  DeviceSchedule:{
    __filename: "../js/views/deviceViews/elements/DeviceSchedule.tsx",
    Sync_schedules_from_Crown:  () => { return "Sync schedules from Crownstone" },
    Schedule:                   () => { return "Schedule" },
    Add_your_first_scheduled_:  () => { return arguments[0] ? "Add your first scheduled action by tapping on the big icon in the center!" : "You do not have permission to create schedules." },
  },
  DeviceSummary:{
    __filename: "../js/views/deviceViews/elements/DeviceSummary.tsx",
    Searching___:               () => { return "Searching..." },
    Once_I_hear_from_this_Cro:  () => { return "Once I hear from this Crownstone, the button will reappear." },
  },
  DeviceUpdate:{
    __filename: "../js/views/deviceViews/elements/DeviceUpdate.tsx",
    Lets_get_started_:          () => { return "Let's get started!" },
  },
  DeviceWhatsNew:{
    __filename: "../js/views/deviceViews/elements/DeviceWhatsNew.tsx",
    Update_Complete_:           () => { return "Update Complete!" },
    Whats_New:                  () => { return "What's New" },
  },
  DfuDeviceEntry:{
    __filename: "../js/views/components/deviceEntries/DfuDeviceEntry.tsx",
    _Very_Near_:                () => { return "(Very Near)" },
    _Near_:                     () => { return "(Near)" },
    _Visible_:                  () => { return "(Visible)" },
    _Barely_visible_:           () => { return "(Barely visible)" },
    _Too_far_away_:             () => { return "(Too far away)" },
  },
  DfuOverlay:{
    __filename: "../js/views/overlays/DfuOverlay.tsx",
    __:                         () => { return arguments[0] + " %" },
  },
  DiagnosticUtil:{
    __filename: "../js/views/settingsViews/diagnostics/DiagnosticUtil.tsx",
    No:                         () => { return "No" },
    Yes:                        () => { return "Yes" },
    ____:                       () => { return arguments[0] + (arguments[1] ? "..." : ".") },
  },
  Diagnostics:{
    __filename: "../js/views/overlays/WhatsNew/2.2.0/Diagnostics.tsx",
    Crownstone_Diagnostics:     () => { return "Crownstone Diagnostics" },
    Sometimes__things_dont_se:  () => { return "Sometimes, things don't seem to work as they should...\n\n" + "Since everything works via invisible signals, it's difficult to determine what the problem is!\n\n" + "The Diagnostics are here to help you discover what the problem could be!\n\n" + "You can find them in the settings menu!\n\n" },
  },
  Dimmer:{
    __filename: "../js/views/overlays/WhatsNew/2.0.0/Dimmer.tsx",
    Dimmer_is_Here_:            () => { return "Dimmer is Here!" },
    You_can_enable_dimming_pe:  () => { return "You can enable dimming per Crownstone in its settings." },
    Set_the_mood_just_right__:  () => { return "Set the mood just right!" },
  },
  DimmerButton:{
    __filename: "../js/views/components/DimmerButton.tsx",
    ____:                       () => { return "(" + arguments[0] + " %)" },
  },
  Dropdown:{
    __filename: "../js/views/components/editComponents/Dropdown.tsx",
    Cancel:                     () => { return "Cancel" },
    Done:                       () => { return "Done" },
  },
  EditableItem:{
    __filename: "../js/views/components/EditableItem.tsx",
    ___UNHANDLED_for_:          () => { return arguments[0] + " - UNHANDLED for " + arguments[1] },
  },
  ErrorOverlay:{
    __filename: "../js/views/overlays/ErrorOverlay.tsx",
    Find_Crownstone:            () => { return "Find Crownstone" },
    Crownstone_Hardware_Error:  () => { return "Crownstone Hardware Error" },
    __Yours__:                  () => { return "~ Yours, " + arguments[0] },
  },
  FastSetup:{
    __filename: "../js/views/overlays/WhatsNew/2.1.0/FastSetup.tsx",
    By_speeding_up_the_setup_:  () => { return "By speeding up the setup process in the new 2.1.2 firmware, we’ve fixed issues with certain android phones." },
  },
  FirmwareUpdate:{
    __filename: "../js/views/overlays/WhatsNew/2.0.0/FirmwareUpdate.tsx",
    New_firmware_available_:    () => { return "New firmware available!" },
    The_new_firmware_enables_:  () => { return "The new firmware enables the mesh, the dimmer and it also has a lot of security improvements!\n" + "This update is mandatory to make sure everything will work together." },
  },
  FirmwareUpdateFix:{
    __filename: "../js/views/overlays/WhatsNew/1.10.2/FirmwareUpdateFix.tsx",
    Issues_that_caused_the_ap:  () => { return "Issues that caused the app to crash when the firmware update was finished are now resolved." },
    You_can_safely_update_all:  () => { return "You can safely update all Crownstones now :)" },
  },
  GraphAxis:{
    __filename: "../js/views/components/graph/GraphComponents/GraphAxis.tsx",
    _W_:                        () => { return "(W)" },
  },
  GuidestoneSummary:{
    __filename: "../js/views/deviceViews/elements/GuidestoneSummary.tsx",
    Device_Type_:               () => { return "Device Type:" },
    Guidestone:                 () => { return "Guidestone" },
    Connected_to_Mesh_:         () => { return "Connected to Mesh:" },
    YesNot_Yet:                 () => { return arguments[0] ? "Yes" : "Not Yet" },
    Reachable_:                 () => { return "Reachable:" },
    YesSearching___:            () => { return arguments[0] ? "Yes" : "Searching..." },
  },
  IPhoneXSupport:{
    __filename: "../js/views/overlays/WhatsNew/2.1.0/IPhoneXSupport.tsx",
    iPhone_X_support_:          () => { return "iPhone X support!" },
    Enjoy_the_Crownstone_app_:  () => { return "Enjoy the Crownstone app in all it's glory on the large screen of the iPhone X!" },
  },
  InSphere:{
    __filename: "../js/views/settingsViews/diagnostics/InSphere.tsx",
    Youre_in_your_Sphere_:      () => { return "You're in your Sphere!" },
  },
  LibMessages:{
    __filename: "../js/views/overlays/LibMessages.tsx",
    OK:                         () => { return arguments[0] || "OK" },
  },
  LocalizationDebugCircle:{
    __filename: "../js/views/settingsViews/dev/LocalizationDebugCircle.tsx",
    P__:                        () => { return "P: " + arguments[0] },
    S_______M__:                () => { return "S: " + (arguments[0] || "...") + ("; M: " + arguments[1]) },
  },
  LocalizationSetupStep1:{
    __filename: "../js/views/overlays/LocalizationSetupStep1.tsx",
    Congratulations_:           () => { return "Congratulations!" },
    You_have_added___Crownsto:  () => { return "You have added 4 Crownstones to your Sphere! We can now use the indoor localization at room level!" },
    Weve_added_this_button_to:  () => { return "We've added this button to your overview:" },
    Once_youve_added_all_your:  () => { return "Once you've added all your Crownstones, tap that button to start teaching Crownstone about your home!" },
    OK_:                        () => { return "OK!" },
  },
  LocalizationSetupStep2:{
    __filename: "../js/views/overlays/LocalizationSetupStep2.tsx",
    The_Next_Step:              () => { return "The Next Step" },
    You_can_now_teach__when_y:  () => { return "You can now teach " + arguments[0] + " when you are in certain rooms. " + "This new icon indicates that " + arguments[1] + " is ready to learn how to identify this room!" },
    Once_youre_ready__tap_one:  () => { return "Once you're ready, tap one to start training!" },
    OK:                         () => { return "OK" },
  },
  LocationPermissionOverlay:{
    __filename: "../js/views/overlays/LocationPermissionOverlay.tsx",
    Request_Permission:         () => { return "Request Permission" },
  },
  LockOverlay:{
    __filename: "../js/views/overlays/LockOverlay.tsx",
    OK___:                      () => { return "OK..." },
    Cancel:                     () => { return "Cancel" },
    Lock_:                      () => { return "Lock!" },
    Locking_a_Crownstone:       () => { return "Locking a Crownstone" },
  },
  LockedStateUI:{
    __filename: "../js/views/components/LockedStateUI.tsx",
    Ask_an_admin_nto_unlock_m:  () => { return "Ask an admin\nto unlock me!" },
    Unlocking___:               () => { return "Unlocking..." },
    Done:                       () => { return "Done" },
    Couldnt_unlock____nYou_mu:  () => { return "Couldn't unlock...\nYou must be near." },
    Press_and_hold_nto_unlock:  () => { return "Press and hold\nto unlock!" },
  },
  Locking:{
    __filename: "../js/views/overlays/WhatsNew/2.0.0/Locking.tsx",
    Lock_your_Crownstones_:     () => { return "Lock your Crownstones!" },
    You_can_lock_a_Crownstone:  () => { return "You can lock a Crownstone if you want to be sure it won't be switched." },
    Useful_for_a_fridge__pc_a:  () => { return "Useful for a fridge, pc and more!" },
  },
  Login:{
    __filename: "../js/views/startupViews/Login.tsx",
    Forgot_Password_:           () => { return "Forgot Password?" },
    Log_In:                     () => { return "Log In" },
  },
  LoginSplash:{
    __filename: "../js/views/startupViews/LoginSplash.tsx",
    Register:                   () => { return "Register" },
    Log_In:                     () => { return "Log In" },
    Buy_Crownstones_:           () => { return "Buy Crownstones!" },
    version__:                  () => { return "version: " + arguments[0] },
  },
  Mesh:{
    __filename: "../js/views/overlays/WhatsNew/2.0.0/Mesh.tsx",
    Crownstones_now_Mesh__nLe:  () => { return "Crownstones now Mesh!\nLet the gossip begin!" },
    Your_Crownstones_can_now_:  () => { return "Your Crownstones can now talk to each other.\n\n" + "This feature extends your overall range, improves the ENTER/EXIT Sphere reliability and allows you to switch many Crownstones much faster!" },
  },
  MeshTopology:{
    __filename: "../js/views/overlays/WhatsNew/2.1.0/MeshTopology.tsx",
    Mesh_Topology_Visualizati:  () => { return "Mesh Topology Visualization" },
    Weve_added_a_visualisatio:  () => { return "We've added a visualisation of the mesh network, this feature shows you the quality of the connections between Crownstones within a mesh." },
  },
  MessageEntry:{
    __filename: "../js/views/messaging/MessageEntry.tsx",
    Failed_to_send__tap_to_re:  () => { return "Failed to send, tap to retry." },
    Sending_message___:         () => { return "Sending message..." },
  },
  MessageInbox:{
    __filename: "../js/views/messaging/MessageInbox.tsx",
    You_can_leave_messages_in:  () => { return "You can leave messages in a Sphere or room for your friends to find!" },
    Tap_the_envelope_icon_to_:  () => { return "Tap the envelope icon to create a new message!" },
    Add_some_Crownstones_to_u:  () => { return "Add some Crownstones to use messages!" },
    Add_a_Sphere_to_use_messa:  () => { return "Add a Sphere to use messages!" },
  },
  Messages:{
    __filename: "../js/views/overlays/WhatsNew/1.11.0/Messages.tsx",
    You_can_now_leave_a_messa:  () => { return "You can now leave a message for others or yourself!" },
    Its_like_you_leave_a_digi:  () => { return "It's like you leave a digital sticky note in a room or in a Sphere." },
  },
  MoveRooms:{
    __filename: "../js/views/overlays/WhatsNew/2.2.0/MoveRooms.tsx",
    Custom_screen_positions_:   () => { return "Custom screen positions!" },
    You_can_now_choose_where_:  () => { return "You can now choose where you want your rooms to be placed!\n\n" + "You can find this in the new Sphere menu, under rooms!\n\n" },
  },
  NewDeviceUI:{
    __filename: "../js/views/overlays/WhatsNew/1.10.0/NewDeviceUI.tsx",
    The_Crownstone_settings_h:  () => { return "The Crownstone settings have a new UI. You can swipe left and right on it to see the options. Scroll down for more." },
    You_get_there_by_tapping_:  () => { return "You get there by tapping on the Crownstone in the room overview, and pressing \"settings\"." + "\n\nIn the new overview, tap on the icon to set the device, swipe left for behaviour and the new power usage graph." },
  },
  NewDeviceUIGraph:{
    __filename: "../js/views/overlays/WhatsNew/1.10.0/NewDeviceUIGraph.tsx",
    You_can_now_see_a_running:  () => { return "You can now see a running graph of the power usage of a Crownstone. Scroll down for more." },
    You_access_it_by_swiping_:  () => { return "You access it by swiping left on the new Crownstone UI.\n\nThis graph is a preview of what we've been working on. " + "In future versions you'll be able to navigate it freely, as well as having one overview for the entire Sphere." },
  },
  NewLocalizationSettings:{
    __filename: "../js/views/overlays/WhatsNew/1.10.0/NewLocalizationSettings.tsx",
    There_are_new_settings_to:  () => { return "There are new settings to allow you to use the Crownstone App without localization." },
  },
  NewScheduler:{
    __filename: "../js/views/overlays/WhatsNew/1.10.0/NewScheduler.tsx",
    You_can_tell_the_Crownsto:  () => { return "You can tell the Crownstone to do something at a certain time!" },
    In_order_to_use_the_sched:  () => { return "In order to use the scheduler, the Crownstone will need to update its firmware first. " + "The new firmware should also be available now!" + "\n\nWhen the update is available, the Crownstones in your room will show an up arrow. Press it to start the update process." + "\n\nIf you do not see it right away, check back later to see if the update is available!" },
  },
  NewSphereSettings:{
    __filename: "../js/views/overlays/WhatsNew/2.2.0/NewSphereSettings.tsx",
    New_Sphere_menu_:           () => { return "New Sphere menu!" },
    Press_Edit_in_the_top_rig:  () => { return "Press Edit in the top right corner of the Sphere overview and customize your Sphere!\n\n" },
  },
  NoStones:{
    __filename: "../js/views/settingsViews/diagnostics/NoStones.tsx",
    You_dont_have_any_Crownst:  () => { return "You don't have any Crownstones yet..." },
  },
  NotInSphere:{
    __filename: "../js/views/settingsViews/diagnostics/NotInSphere.tsx",
    Sphere_tests_completed_:    () => { return "Sphere tests completed!" },
    Running_Sphere_tests___:    () => { return "Running Sphere tests..." },
    Initial_tests_completed_:   () => { return "Initial tests completed!" },
    Let_me_run_a_few_more_tes:  () => { return "Let me run a few more tests..." },
  },
  OptionPopup:{
    __filename: "../js/views/components/OptionPopup.tsx",
    Cancel:                     () => { return "Cancel" },
  },
  OptionalSwitchBar:{
    __filename: "../js/views/components/editComponents/OptionalSwitchBar.tsx",
    NULL:                       () => { return "NULL" },
  },
  PhysicsBasedSphereUI:{
    __filename: "../js/views/overlays/WhatsNew/1.10.0/PhysicsBasedSphereUI.tsx",
    The_Sphere_overview_now_p:  () => { return "The Sphere overview now positions the rooms automatically. Scroll down for more." },
    You_can_move_it_around_as:  () => { return "You can move it around as well as zoom in. Double tap the background to reset the camera." },
  },
  ProblemWithCrownstone:{
    __filename: "../js/views/settingsViews/diagnostics/ProblemWithCrownstone.tsx",
    Youre_in_your_Sphere_:      () => { return "You're in your Sphere!" },
  },
  ProblemWithExistingCrownstone:{
    __filename: "../js/views/settingsViews/diagnostics/ProblemWithExistingCrownstone.tsx",
    Problem_with_existing_Cro:  () => { return "Problem with existing Crownstone..." },
  },
  ProblemWithLocalization:{
    __filename: "../js/views/settingsViews/diagnostics/ProblemWithLocalization.tsx",
    Problem_with_localization:  () => { return "Problem with localization..." },
  },
  ProblemWithNewCrownstone:{
    __filename: "../js/views/settingsViews/diagnostics/ProblemWithNewCrownstone.tsx",
    Problem_with_new_Crownsto:  () => { return "Problem with new Crownstone..." },
    Let_me_run_a_few_more_tes:  () => { return "Let me run a few more tests..." },
  },
  ProblemWithOtherCrownstone:{
    __filename: "../js/views/settingsViews/diagnostics/ProblemWithOtherCrownstone.tsx",
    Problem_with_missing_Crow:  () => { return "Problem with missing Crownstone..." },
  },
  Register:{
    __filename: "../js/views/startupViews/Register.tsx",
    By_registering__you_agree:  () => { return "By registering, you agree to our" },
    terms_:                     () => { return "terms" },
    __:                         () => { return "& " },
    privacy_policy:             () => { return "privacy policy" },
  },
  RegisterConclusion:{
    __filename: "../js/views/startupViews/RegisterConclusion.tsx",
    An_email_has_been_sent_to:  () => { return "An email has been sent to:" },
    Please_click_the_link_in_:  () => { return arguments[0] ? "Please click the link in the email and follow the instructions to reset your password." : "After you click the validation link in the email, you can login to the app using your email address." },
    It_can_take_up_to_a_minut:  () => { return "It can take up to a minute for the email to be received. Make sure you check your spam folder as well." },
    OK:                         () => { return "OK" },
  },
  ReviewInitialTests:{
    __filename: "../js/views/settingsViews/diagnostics/ReviewInitialTests.tsx",
    Problems_found__:           () => { return "Problems found.." },
    To_fix_this_well_have_to_:  () => { return "To fix this we'll have to fully re-sync with the Cloud. Press the button below to fix this!" },
    Restore_database:           () => { return "Restore database" },
    Your_phone_is_currently_n:  () => { return "Your phone is currently not scanning for the beacon signals sent by the Crownstones.\n\n" + "To fix this, make sure the Bluetooth is on, the permission for Location Services is set to \"always\" and try to restart the app.\n\n" + "Press the button below to fully quit the app." },
    Quit_app_now:               () => { return "Quit app now" },
    Running_initial_tests___:   () => { return "Running initial tests..." },
  },
  RoomBanner:{
    __filename: "../js/views/components/RoomBanner.tsx",
    Not_in_Sphere:              () => { return "Not in Sphere" },
    Nobody_Present:             () => { return "Nobody Present" },
    No_Crownstones_in_this_ro:  () => { return "No Crownstones in this room" },
    _Crownstone:                () => { return arguments[0] + " Crownstone" },
    _Crownstones:               () => { return arguments[0] + " Crownstones" },
    _W:                         () => { return arguments[0] + " W" },
  },
  RoomCircle:{
    __filename: "../js/views/components/RoomCircle.tsx",
    _W:                         () => { return arguments[0] + " W" },
  },
  RoomDeleted:{
    __filename: "../js/views/static/RoomDeleted.tsx",
    Room_Deleted_:              () => { return "Room Deleted." },
  },
  RoomImages:{
    __filename: "../js/views/overlays/WhatsNew/2.1.0/RoomImages.tsx",
    Customize_Rooms_:           () => { return "Customize Rooms!" },
    If_youre_the_admin_of_you:  () => { return "If you're the admin of your Sphere, this update enables to add a picture to a room!" },
  },
  RoomList:{
    __filename: "../js/views/components/RoomList.tsx",
    Number_of_Crownstones__:    () => { return "Number of Crownstones: " + arguments[0] },
  },
  RoomTraining_explanation:{
    __filename: "../js/views/roomViews/trainingComponents/RoomTraining_explanation.tsx",
    OK__so_its_a__room__Lets_:  () => { return "OK, so it's a " + arguments[0] + " room. Let's start training " + arguments[1] + "!" },
    Walk_around_the_room_with:  () => { return "Walk around the room with your phone in your hand. " + "Try to get to every spot in the room, near the walls as well and through the center. " + "The teaching process takes " + arguments[0] + " seconds and you can see the progress on your screen." },
    Press_the_button_below_to:  () => { return "Press the button below to get started!" },
  },
  RoomTraining_finished:{
    __filename: "../js/views/roomViews/trainingComponents/RoomTraining_finished.tsx",
    Finished_learning_about_t:  () => { return "Finished learning about this room!" },
    Once_you_have_taught__all:  () => { return "Once you have taught " + arguments[0] + " all the rooms, " + arguments[1] + " will start doing " + arguments[2] + " best to determine in which room you are!\n\nPress the button below to go back!" },
  },
  RoomTraining_roomSize:{
    __filename: "../js/views/roomViews/RoomTraining_roomSize.tsx",
    To_let__find_you_in___we_:  () => { return "To let " + arguments[0] + " find you in " + arguments[1] + ", we need to help " + arguments[2] + " a little!" },
    How_large_is_this_room_:    () => { return "How large is this room?" },
    Large_rooms_take_a_bit_mo:  () => { return "Large rooms take a bit more time to learn about than small rooms." },
  },
  RoomTraining_training:{
    __filename: "../js/views/roomViews/trainingComponents/RoomTraining_training.tsx",
    Walk_around_the_room_so__:  () => { return "Walk around the room so " + arguments[0] + " can learn to locate you within it. Each beat " + arguments[1] + " learns a bit more about the room!" },
  },
  SeparatedItemList:{
    __filename: "../js/views/components/SeparatedItemList.tsx",
    UNKNOWN_TYPE:               () => { return "UNKNOWN TYPE" },
  },
  SettingsBleTroubleshootingAndroid:{
    __filename: "../js/views/settingsViews/troubleshooting/SettingsBleTroubleshootingAndroid.tsx",
    Troubleshooting:            () => { return "Troubleshooting" },
    Sometimes__the_Bluetooth_:  () => { return "Sometimes, the Bluetooth on your iPhone can act up, refuse to work or be stuck on a connection." },
    Unfortunately__sometimes_:  () => { return "Unfortunately, sometimes things go wrong, and we're not allowed by the phone manufacturers reset the Bluetooth chip (and rightfully so!).\n\n" + "There are a few things you can do however, to fix most of these issues. This guide will walk you through the steps to reset your Bluetooth on iOS." },
    Im_sure_youre_all_familia:  () => { return "I'm sure you're all familiar with the Apple Control Center. If you're not, it's this one:" },
    There_is_a_Bluetooth_icon:  () => { return "There is a Bluetooth icon on there, but if you press it, you do NOT disable Bluetooth. You only tell it to stop connecting:" },
    To_reset_Bluetooth_the_ri:  () => { return "To reset Bluetooth the right way, we have to go into the settings of your iPhone by pressing on the cogwheel icon:" },
    In_the_settings_overview_:  () => { return "In the settings overview, we select the Bluetooth bar:" },
    Finally__in_the_Bluetooth:  () => { return "Finally, in the Bluetooth menu, we disable Bluetooth by tapping on the switch:" },
    The_result_should_be_:      () => { return "The result should be:" },
    You_wait_for_a_few_second:  () => { return "You wait for a few seconds and then turn Bluetooth back on. Your Bluetooth has now been restarted, which will solve most related problems.\n\n" + "If any issues persist, you can try restarting your iPhone or run the Diagnostics in the Crownstone app.\n\n" + "If none of this works for you, contact us at team@crownstone.rocks and we'd be happy to help you solve the issue!" },
    Enjoy_using_your_Crownsto:  () => { return "Enjoy using your Crownstones!" },
  },
  SettingsBleTroubleshootingIOS:{
    __filename: "../js/views/settingsViews/troubleshooting/SettingsBleTroubleshootingIOS.tsx",
    Troubleshooting:            () => { return "Troubleshooting" },
    Sometimes__the_Bluetooth_:  () => { return "Sometimes, the Bluetooth on your iPhone can act up, refuse to work or be stuck on a connection." },
    Unfortunately__sometimes_:  () => { return "Unfortunately, sometimes things go wrong, and we're not allowed by the phone manufacturers reset the Bluetooth chip (and rightfully so!).\n\n" + "There are a few things you can do however, to fix most of these issues. This guide will walk you through the steps to reset your Bluetooth on iOS." },
    Im_sure_youre_all_familia:  () => { return "I'm sure you're all familiar with the Apple Control Center. If you're not, it's this one:" },
    There_is_a_Bluetooth_icon:  () => { return "There is a Bluetooth icon on there, but if you press it, you do NOT disable Bluetooth. You only tell it to stop connecting:" },
    To_reset_Bluetooth_the_ri:  () => { return "To reset Bluetooth the right way, we have to go into the settings of your iPhone by pressing on the cogwheel icon:" },
    In_the_settings_overview_:  () => { return "In the settings overview, we select the Bluetooth bar:" },
    Finally__in_the_Bluetooth:  () => { return "Finally, in the Bluetooth menu, we disable Bluetooth by tapping on the switch:" },
    The_result_should_be_:      () => { return "The result should be:" },
    You_wait_for_a_few_second:  () => { return "You wait for a few seconds and then turn Bluetooth back on. Your Bluetooth has now been restarted, which will solve most related problems.\n\n" + "If any issues persist, you can try restarting your iPhone or run the Diagnostics in the Crownstone app.\n\n" + "If none of this works for you, contact us at team@crownstone.rocks and we'd be happy to help you solve the issue!" },
    Enjoy_using_your_Crownsto:  () => { return "Enjoy using your Crownstones!" },
  },
  SettingsDiagnostics:{
    __filename: "../js/views/settingsViews/SettingsDiagnostics.tsx",
    Since_everything_communic:  () => { return "Since everything communicates via wireless signals, it is sometimes a little difficult to see what is happening if something goes wrong." },
    I_can_run_a_few_tests_to_:  () => { return "I can run a few tests to check if everything is working as intended! Press the button below to start the tests." },
    Run_diagnostics:            () => { return "Run diagnostics" },
    Running_initial_tests___:   () => { return "Running initial tests..." },
    Diagnostics:                () => { return "Diagnostics" },
  },
  SettingsFAQ:{
    __filename: "../js/views/settingsViews/SettingsFAQ.tsx",
    Sometimes_something_goes_:  () => { return "Sometimes something goes wrong in the persisting of the local data.\n\nTo solve this you can try to redownload the data from the Cloud. Press the button below to do this." },
    Sometimes_something_goes_w: () => { return "Sometimes something goes wrong in the persisting of the local data.\n\nTo solve this you can try to redownload the data from the Cloud. Press the button below to do this." },
    It_could_be_that_youre_no:  () => { return "It could be that you're not close enough to the nearest Crownstone. Try going closer.\n\n" + "If that does not work, try to restarting your Bluetooth, restarting the App or even restarting your Phone.\n\n" + "If that does not work either, you can try to press the button below to resync with the Cloud. This will delete all your local preferences and replace it by the data in the Cloud." },
    Only_use_this_as_a_last_r:  () => { return "Only use this as a last resort. \n\n- Tap the button below and follow the instructions.\n" + "- If something goes wrong, read the error message. It explains what is going on." },
  },
  SettingsFactoryResetStep1:{
    __filename: "../js/views/settingsViews/SettingsFactoryResetStep1.tsx",
    If_youre_physically_next_:  () => { return "If you're physically next to the Crownstone, you can reset it to factory defaults." },
    Please_take_the_Crownston:  () => { return "Please take the Crownstone out of the outlet, wait 5 seconds, and plug it back in. Hold your phone close to it and press Next to continue." },
  },
  SettingsFactoryResetStep2:{
    __filename: "../js/views/settingsViews/SettingsFactoryResetStep2.tsx",
    Hold_your_phone_next_to_t:  () => { return "Hold your phone next to the Crownstone." },
  },
  SettingsLocalizationDebug:{
    __filename: "../js/views/settingsViews/dev/SettingsLocalizationDebug.tsx",
    You_have_to_be_in_a_Spher:  () => { return "You have to be in a Sphere" },
    _Crownstones_in_vector:     () => { return arguments[0] + " Crownstone" + (arguments[1] ? "s" : "") + " in vector" },
  },
  SettingsMeshOverview:{
    __filename: "../js/views/settingsViews/SettingsMeshOverview.tsx",
    Here_you_can_see_which_Cr:  () => { return "Here you can see which Crownstones in your Sphere are connected via the Mesh." },
    It_can_take_some_time_for:  () => { return "It can take some time for me to hear what is connected to what. Make sure your phone is near Crownstones to hear they are connected to. If one Crownstone cannot see the others, try moving it closer to the nearest one." },
    Mesh_Networks_:             () => { return "Mesh Networks:" },
  },
  SettingsMeshTopology:{
    __filename: "../js/views/settingsViews/SettingsMeshTopology.tsx",
    No_Crownstones_in_Sphere_:  () => { return "No Crownstones in Sphere \"" + arguments[0] + "\" yet." },
  },
  SettingsMeshTopologyHelp:{
    __filename: "../js/views/settingsViews/SettingsMeshTopologyHelp.tsx",
    Mesh_Topology:              () => { return "Mesh Topology" },
    Crownstones_can_talk_to_e:  () => { return "Crownstones can talk to each other, and a group of Crownstones chatting makes up a mesh network." + "\n\nThey can only talk to each other if they are in range of each other. The topology view shows you which Crownstones can talk to each other." + "\n\nThe icons show the Crownstone with its device icon as shown here:" },
    Every_other_second_the_Cr:  () => { return "Every other second the Crownstones will advertise the state of other Crownstones, as well as how well they can hear them. " + "This information is gathered by your phone when the app is open (on the foreground)." + "\n\nIf your phone can hear this information from a Crownstone, the border of the circle will become green:" },
    Every_second__the_backgro:  () => { return "Every second, the background will blink green to show you you're still in range of that Crownstone." + "\n\nIf you tap on the bubble, it will expand to show you its name and the room that it's currently in:" },
    The_connectivity_among_Cr:  () => { return "The connectivity among Crownstones can only be heard directly. If there are unconnected Crownstones in the overview and " + "you want to check how well they are connected to rest of the network, you'll have to be in range of that Crownstone to check." + "\n\nAs an alternative, you can press the 'Networks' button in the top right to see which Crownstones are in which network." + "\n\nThese networks will be cleared and rediscovered every time you reopen the app as an ensurance that the mesh networks are always up te date." },
    Enjoy_the_Mesh_:            () => { return "Enjoy the Mesh!" },
  },
  SettingsOverview:{
    __filename: "../js/views/settingsViews/SettingsOverview.tsx",
    Crownstone_:                () => { return "Crownstone" },
    terms_:                     () => { return "terms" },
    __:                         () => { return "& " },
    privacy_policy:             () => { return "privacy policy" },
    version__:                  () => { return "version: " + arguments[0] },
  },
  SettingsRedownloadFromCloud:{
    __filename: "../js/views/settingsViews/SettingsRedownloadFromCloud.tsx",
    Replace_local_data_with_C:  () => { return "Replace local data with Cloud data" },
    To_restore_your_local_dat:  () => { return "To restore your local data with the Cloud data, press the button below. If you don't want to do this, just go back to the help menu.\n\n" + "Replacing the local data with the 'fresh' Cloud data might solve some issues you experience in your app." },
    Im_sure__do_it_:            () => { return "I'm sure, do it!" },
  },
  SettingsStoneBleDebug:{
    __filename: "../js/views/settingsViews/dev/SettingsStoneBleDebug.tsx",
    No_Data:                    () => { return arguments[0] || "No Data" },
  },
  SetupDeviceEntry:{
    __filename: "../js/views/components/deviceEntries/SetupDeviceEntry.tsx",
    _Very_Near_:                () => { return "(Very Near)" },
    _Near_:                     () => { return "(Near)" },
    _Visible_:                  () => { return "(Visible)" },
    _Barely_visible_:           () => { return "(Barely visible)" },
    _Too_far_away_:             () => { return "(Too far away)" },
  },
  SetupShared:{
    __filename: "../js/views/settingsViews/SetupShared.tsx",
    Next:                       () => { return "Next" },
    Start_setup:                () => { return "Start setup" },
    Skip:                       () => { return "Skip" },
    Cancel:                     () => { return "Cancel" },
  },
  SideBar:{
    __filename: "../js/views/components/sideMenu/SideBar.tsx",
    Crownstone:                 () => { return "Crownstone" },
  },
  Sphere:{
    __filename: "../js/views/main/Sphere.tsx",
    No_Crownstones_added_yet_:  () => { return "No Crownstones added yet!" },
    Ask_the_admin_of_this_Sph:  () => { return "Ask the admin of this Sphere to add some!" },
    Get_close_to_a_new_Crowns:  () => { return "Get close to a new Crownstone and it will appear here automatically!" },
    If_nothing_happens__ensur:  () => { return "If nothing happens, ensure the Crownstone is powered on and not paired with another user.\n\n" + (arguments[0] ? "More help is available under 'help' in the side menu." : "More help is available in the help menu in the settings.") },
  },
  SphereDeleted:{
    __filename: "../js/views/static/SphereDeleted.tsx",
    Sphere_Deleted_:            () => { return "Sphere Deleted." },
  },
  SphereOverview:{
    __filename: "../js/views/main/SphereOverview.tsx",
    No_Spheres_available_:      () => { return "No Spheres available." },
    Press_Edit_in_the_upper_r:  () => { return "Press Edit in the upper right corner to create your own Sphere or wait to be added to those of others." },
  },
  SphereRoomArranger:{
    __filename: "../js/views/main/editSubviews/SphereRoomArranger.tsx",
    Solve_Positions:            () => { return "Solve Positions" },
  },
  Splash:{
    __filename: "../js/views/startupViews/Splash.tsx",
    version__:                  () => { return "version: " + arguments[0] },
  },
  StatusCommunication:{
    __filename: "../js/views/main/StatusCommunication.tsx",
    New_Crownstone_Detected__:  () => { return "New Crownstone Detected! Tap on it!" },
    No_Crownstones_in_range_:   () => { return "No Crownstones in range." },
    I_see_:                     () => { return "I see " + arguments[0] },
    _so_the_indoor_localizati:  () => { return " so the indoor localization is running." },
    I_see_only_:                () => { return "I see only " + arguments[0] },
    _so_I_paused_the_indoor_l:  () => { return " so I paused the indoor localization." },
    Not_all_rooms_have_been_t:  () => { return "Not all rooms have been trained so I can\'t do indoor localization." },
    Not_enough_Crownstones_pl:  () => { return "Not enough Crownstones placed in rooms to do indoor localization." },
    I_can_see_:                 () => { return "I can see " + arguments[0] },
    Looking_for_Crownstones__:  () => { return "Looking for Crownstones..." },
  },
  StoneDeleted:{
    __filename: "../js/views/static/StoneDeleted.tsx",
    Stone_Deleted_:             () => { return "Stone Deleted." },
  },
  SwitchBar:{
    __filename: "../js/views/components/editComponents/SwitchBar.tsx",
    EXPERIMENTAL:               () => { return arguments[0] || "EXPERIMENTAL" },
  },
  SwitchCraftInformation:{
    __filename: "../js/views/deviceViews/elements/SwitchCraftInformation.tsx",
    Switchcraft_is_a_new__exp:  () => { return "Switchcraft is a new, experimental feature of the Crownstone that allows you to switch your lights with both Crownstone and an existing wall switch." + "\n\nIt is designed for Built-in Crownstones that are mounted in a ceiling light fixture." + "\n\nUsually, if you have a Crownstone in your ceiling light and the wall switch is off, there is no power to the Crownstone so it cannot switch the light." + "\n\nLet's take a look a the situation before Crownstone:" },
    The_symbols_shown_have_th:  () => { return "The symbols shown have the following meaning:" },
    Lamp:                       () => { return "Lamp" },
    Mains:                      () => { return "Mains" },
    Switch:                     () => { return "Switch" },
    Built_in_nCrownstone:       () => { return "Built-in\nCrownstone" },
    After_installing_the_buil:  () => { return "After installing the built-in Crownstone it should look like this:" },
    The_adaptation_in_the_ima:  () => { return "The adaptation in the image above shows the required change to enable Switchcraft. Most switches have 3 ports, where each port can have 2 slots. Let's take a look a the switch below:" },
    At_the_top__where_the_bro:  () => { return "At the top, where the brown wire goes in, that's where the power comes from the mains. In most cases, there will be one wire going out: to the light." + "\n\nIn the next picture we see the adaptation " + "which will allow this switch to be used with Switchcraft:" },
    Thats_all__When_youre_goi:  () => { return "That's all! When you're going to upgrade your existing wall switches to work with Switchcraft, make sure that there is NO POWER ON THE MAINS!" + "\n\nSince this is an experimental feature, we would like to get your feedback at team@crownstone.rocks." },
    Enjoy_Switchcraft_:         () => { return "Enjoy Switchcraft!" },
  },
  Switchcraft:{
    __filename: "../js/views/overlays/WhatsNew/2.1.0/Switchcraft.tsx",
    Introducing___:             () => { return "Introducing..." },
    Switchcraft_allows_you_to:  () => { return "Switchcraft allows you to use most wall switches with your built-in Crownstones. " + "If the Crownstone is connected to a ceiling light, you can modify your wall switch a little to use it with the Crownstone.\n\n" + "We have tested this feature a lot and are happy with the results so far! Since we can't test all possible wall switches, Switchcraft is " + "first released as a beta feature. Go to 'My Account' and select 'Join Beta Program' to enable the Switchcraft option for built-in Crownstones!" },
  },
  SyncingSchedules:{
    __filename: "../js/views/overlays/WhatsNew/1.10.2/SyncingSchedules.tsx",
    You_can_now_download_the_:  () => { return "You can now download the schedules from the Crownstone." },
    IMPORTANT__ALL_EXISTING_S:  () => { return "IMPORTANT: ALL EXISTING SCHEDULES NEED TO BE SYNCED UPDATED." },
    Use_this_to_change_or_del:  () => { return "Use this to change or delete schedules on the Crownstone if they are not in the app." },
  },
  SyncingSchedulesToTheCloud:{
    __filename: "../js/views/overlays/WhatsNew/1.11.0/SyncingSchedulesToTheCloud.tsx",
    Schedules_are_now_synchro:  () => { return "Schedules are now synchronized between phones via the cloud!" },
    This_happens_automaticall:  () => { return "This happens automatically so everyone will see the same schedules!" },
  },
  TapToToggleCalibration:{
    __filename: "../js/views/overlays/TapToToggleCalibration.tsx",
    Back:                       () => { return "Back" },
  },
  TimezoneScheduler:{
    __filename: "../js/views/overlays/WhatsNew/1.10.2/TimezoneScheduler.tsx",
    Schedules_now_support_day:  () => { return "Schedules now support daylight saving time and timezones." },
    IMPORTANT__ALL_EXISTING_S:  () => { return "IMPORTANT: ALL EXISTING SCHEDULES NEED TO BE SYNCED UPDATED." },
    _______________Because_th:  () => { return "Because the time sent to the Crownstone has changed,              the existing schedules will fire a the wrong time.              Sync, then change the time to fix it!" },
  },
  ToonAdd:{
    __filename: "../js/views/thirdParty/toon/ToonAdd.tsx",
    Submit:                     () => { return "Submit" },
    Working____:                () => { return "Working...." },
    If_something_went_wrong__:  () => { return "If something went wrong, tap here if you want to manually input the code." },
    Connect_with_Toon_:         () => { return "Connect with Toon!" },
    Sometimes__Toon_is_set_to:  () => { return "Sometimes, Toon is set to \"Away\" while you're still there...\n\n... but Crownstone can ensure that it is set to \"Home\" as long as you're home!" },
    This_application_uses_the:  () => { return "This application uses the Toon API, follows the guiding principles for using the Toon API, but has not been developed by Toon." },
  },
  ToonIsNew:{
    __filename: "../js/views/overlays/WhatsNew/2.2.0/ToonIsNew.tsx",
    Crownstone_works_with_Too:  () => { return "Crownstone works with Toon" },
    Sometimes__Toon_is_set_to:  () => { return "Sometimes, Toon is set to \"Away\" while you're still there...\n\n" + "...but Crownstone can set it to \"Home\" as long as you're home!\n\n" + "Let your phone tell Toon when it's home!\n\n\n" },
  },
  ToonOverview:{
    __filename: "../js/views/thirdParty/toon/ToonOverview.tsx",
    There_are_multiple_Toons_:  () => { return "There are multiple Toon's on your account.\n\nPick one to configure it!" },
  },
  ToonSettings:{
    __filename: "../js/views/thirdParty/toon/ToonSettings.tsx",
    Crownstone_and_Toon_are_c:  () => { return "Crownstone and Toon are connected!" },
    Sometimes__Toon_is_set_to:  () => { return "Sometimes, Toon is set to \"Away\" while you're still there..." },
    ___but_Crownstone_can_set:  () => { return "...but Crownstone can set it to \"Home\" as long as you're home!" },
    Should_this_phone_tell_To:  () => { return "Should this phone tell Toon when it's home?" },
    This_application_uses_the:  () => { return "This application uses the Toon API, follows the guiding principles for using the Toon API, but has not been developed by Toon." },
  },
  TutorialBehaviour:{
    __filename: "../js/views/tutorialViews/elements/TutorialBehaviour.tsx",
    Behaviour:                  () => { return "Behaviour" },
    Behaviour_of_Crownstones_:  () => { return "Behaviour of Crownstones indicates how it responds to your location." + "\n\nYou can tell the Crownstone to turn on or off when you... " + "\n\n- Enter or exit the sphere." + "\n- Get near or move away from it." + "\n- Enter or exit a room (with 4 or more)." },
  },
  TutorialDevices:{
    __filename: "../js/views/tutorialViews/elements/TutorialDevices.tsx",
    Device_Types:               () => { return "Device Types" },
    You_can_add_a_device_type:  () => { return "You can add a device type to a Crownstone. These device types have behaviour, icons and names." + "\n\nYou can add a single device type to multiple Crownstones. Behaviour of device types will overrule behaviour of Crownstones." },
    Got_it_:                    () => { return "Got it!" },
  },
  TutorialGetStarted:{
    __filename: "../js/views/tutorialViews/elements/TutorialGetStarted.tsx",
    Let_s_get_started_:         () => { return "Let\'s get started!" },
    In_this_introduction_we_w:  () => { return "In this introduction we will explain the basics like spheres, behaviour and permissions." + "\n\nSwipe this screen to the left for a brief introduction of the app!" },
  },
  TutorialLocalization:{
    __filename: "../js/views/tutorialViews/elements/TutorialLocalization.tsx",
    Indoor_Localization:        () => { return "Indoor Localization" },
    Your_phone_can_determine_:  () => { return "Your phone can determine how far it is from every Crownstone." + "\n\nIf you have 4 or more Crownstones, this information can be combined to determine in which room you are." + "\n\nWe are only using the Bluetooth iBeacon messages sent from the Crownstones, not your GPS. For this, we require the background location permissions." },
  },
  TutorialSphere:{
    __filename: "../js/views/tutorialViews/elements/TutorialSphere.tsx",
    Spheres:                    () => { return "Spheres" },
    Your_sphere_is_your_colle:  () => { return "Your sphere is your collection of Crownstones. This is usually your house, office or personal space." + "\n\nOnly one sphere can be active at a time. It contains rooms, Crownstones, device types and possibly other users." + "\n\nYou can invite other people (as admins, members or guests) to your sphere so they can use your Crownstones." },
  },
  WhatsNew:{
    __filename: "../js/views/overlays/WhatsNew/1.10.0/WhatsNew.tsx",
    One_of_the_new_things_is_:  () => { return "One of the new things is the What's New popup!" },
    Swipe_left_to_see_more_of:  () => { return "Swipe left to see more of the new features." },
  },
  WhatsNewOverlay:{
    __filename: "../js/views/overlays/WhatsNewOverlay.tsx",
    Your_App_was_updated_:      () => { return "Your App was updated!" },
  },
  ZoomInstructionOverlay:{
    __filename: "../js/views/main/ZoomInstructionOverlay.tsx",
    You_can_go_to_the_sphere_:  () => { return "You can go to the sphere overview just by zooming out!" },
    Youll_have_to_do_this_onc:  () => { return "You'll have to do this once to get rid of this pop up!" },
    Ill_try_it_:                () => { return "I'll try it!" },
  },
}