export default {
  AddItemsToSphere:{
    __filename: "../js/views/main/AddItemsToSphere.tsx",
    _Adding_a_Crownstone__Plu_header: () => { return "Adding a Crownstone" },
    _Adding_a_Crownstone__Plu_body: () => { return "Plug the new Crownstone in and hold your phone close to it (touching it). " + "It will automatically show up in the main overview. I'll take you there now." + "\n\nYou don't have to press this button for each Crownstone you add :)." },
    _Adding_a_Crownstone__Plu_left: () => { return "Buy" },
    _Adding_a_Crownstone__Plu_right: () => { return "OK" },
  },
  AiStart:{
    __filename: "../js/views/startupViews/AiStart.tsx",
    _Ehmm_____arguments_______header: () => { return "Ehmm " + arguments[0] + ".. :(" },
    _Ehmm_____arguments_______body: () => { return "I'd really like a name... Could you give me one please?" },
    _Ehmm_____arguments_______left: () => { return "Right Away!" },
    arguments___arguments___n_header: () => { return arguments[0] },
    arguments___arguments___n_body: () => { return arguments[0] },
  },
  ApplianceAdd:{
    __filename: "../js/views/deviceViews/ApplianceAdd.tsx",
    _Device_name_must_be_at_l_header: () => { return "Device name must be at least 1 character long." },
    _Device_name_must_be_at_l_body: () => { return "Please change the name and try again." },
    _Device_name_must_be_at_l_left: () => { return "OK" },
    _Encountered_Cloud_Issue__header: () => { return "Encountered Cloud Issue." },
    _Encountered_Cloud_Issue__body: () => { return "We cannot create an Appliance in the Cloud. Please try again later." },
    _Encountered_Cloud_Issue__left: () => { return "OK" },
  },
  ApplianceSelection:{
    __filename: "../js/views/deviceViews/ApplianceSelection.tsx",
    _Are_you_sure___We_will_b_header: () => { return "Are you sure?" },
    _Are_you_sure___We_will_b_body: () => { return "We will be automatically remove \"" + arguments[0] + "\" from any Crownstones using it." },
    _Are_you_sure___We_will_b_left: () => { return "Cancel" },
    _Are_you_sure___We_will_b_right: () => { return "Delete" },
    _Encountered_Cloud_Issue__header: () => { return "Encountered Cloud Issue." },
    _Encountered_Cloud_Issue__body: () => { return "We cannot delete this Appliance in the Cloud. Please try again later." },
    _Encountered_Cloud_Issue__left: () => { return "OK" },
  },
  CameraRollView:{
    __filename: "../js/views/cameraViews/CameraRollView.tsx",
    _I_do_not_have_access_to__header: () => { return "I do not have access to your pictures..." },
    _I_do_not_have_access_to__body: () => { return "You can give me access by going to the settings on your phone, select Crownstone and enable the picture permissions." },
    _I_do_not_have_access_to__left: () => { return "OK" },
  },
  DeviceBehaviourEdit:{
    __filename: "../js/views/deviceViews/DeviceBehaviourEdit.tsx",
    _Near_behaviour_disabled__header: () => { return "Near behaviour disabled: define range first." },
    _Near_behaviour_disabled__body: () => { return "You defined behaviour for being near and move away from a Crownstone. This feature is disabled until you define what 'near' is using the blue button." },
    _Near_behaviour_disabled__left: () => { return "Later" },
    _Near_behaviour_disabled__right: () => { return "OK" },
    _Im_not_sure_yet_____I_co_header: () => { return "I'm not sure yet..." },
    _Im_not_sure_yet_____I_co_body: () => { return "I could not collect enough points.. Could you try again?" },
    _Im_not_sure_yet_____I_co_left: () => { return "OK" },
    _Great___Ill_make_sure_to_header: () => { return "Great!" },
    _Great___Ill_make_sure_to_body: () => { return "I'll make sure to respond when you are within this range! When you move out and move back in I can start to respond!" },
    _Great___Ill_make_sure_to_left: () => { return "OK" },
    _How_near_is_near___You_c_header: () => { return "How near is near?" },
    _How_near_is_near___You_c_body: () => { return "You can choose the switching point between near and far! After you press OK you have 5 seconds to hold your phone where it usually is (in your pocket?)" },
    _How_near_is_near___You_c_left: () => { return "Cancel" },
    _How_near_is_near___You_c_right: () => { return "OK" },
  },
  DeviceEdit:{
    __filename: "../js/views/deviceViews/DeviceEdit.tsx",
    _Permission_Required__Onl_header: () => { return "Permission Required" },
    _Permission_Required__Onl_body: () => { return "Only Admins have permission to enable dimming on a Crownstone." },
    _Permission_Required__Onl_left: () => { return "OK" },
    _Are_you_sure___Removing__header: () => { return "Are you sure?" },
    _Are_you_sure___Removing__body: () => { return "Removing a Crownstone from the sphere will revert it to it's factory default settings." },
    _Are_you_sure___Removing__left: () => { return "Cancel" },
    _Are_you_sure___Removing__right: () => { return "Remove" },
    _Cant_see_this_one___We_c_header: () => { return "Can't see this one!" },
    _Cant_see_this_one___We_c_body: () => { return "We can't find this Crownstone while scanning. Can you move closer to it and try again? If you want to remove it from your Sphere without resetting it, press Delete anyway." },
    _Cant_see_this_one___We_c_left: () => { return "Delete anyway" },
    _Cant_see_this_one___We_c_right: () => { return "Cancel" },
    _Encountered_Cloud_Issue__header: () => { return "Encountered Cloud Issue." },
    _Encountered_Cloud_Issue__body: () => { return "We cannot delete this Crownstone in the cloud. Please try again later" },
    _Encountered_Cloud_Issue__left: () => { return "OK" },
    _Encountered_a_problem____header: () => { return "Encountered a problem." },
    _Encountered_a_problem____body: () => { return "We cannot Factory reset this Crownstone. Unfortunately, it has already been removed from the cloud. " + "Try deleting it again or use the factory reset procedure to put it in setup mode." },
    _Encountered_a_problem____left: () => { return "OK" },
    _Encountered_Cloud_Issue___header: () => { return "Encountered Cloud Issue." },
    _Encountered_Cloud_Issue___body: () => { return "We cannot delete this Crownstone in the cloud. Please try again later" },
    _Encountered_Cloud_Issue___left: () => { return "OK" },
    _Success__arguments___OKn_header: () => { return "Success!" },
    _Success__arguments___OKn_body: () => { return arguments[0] },
    _Success__arguments___OKn_left: () => { return "OK" },
    _Crownstone_Locked__You_h_header: () => { return "Crownstone Locked" },
    _Crownstone_Locked__You_h_body: () => { return "You have to unlock the Crownstone before " + (arguments[0] ? "enabling" : "disabling") + " dimming." },
    _Crownstone_Locked__You_h_left: () => { return "OK" },
    _Cant_see_this_Crownstone_header: () => { return "Can't see this Crownstone!" },
    _Cant_see_this_Crownstone_body: () => { return "You have to be in range of Crownstone before " + (arguments[0] ? "enabling" : "disabling") + " dimming." },
    _Cant_see_this_Crownstone_left: () => { return "OK" },
    _Im_sorry_____I_couldnt_d_header: () => { return "I'm sorry..." },
    _Im_sorry_____I_couldnt_d_body: () => { return "I couldn't disable dimming on this Crownstone. Please move closer and try again." },
    _Im_sorry_____I_couldnt_d_left: () => { return "OK" },
    _Im_sorry_____I_couldnt_e_header: () => { return "I'm sorry..." },
    _Im_sorry_____I_couldnt_e_body: () => { return "I couldn't enable dimming on this Crownstone. Please move closer and try again." },
    _Im_sorry_____I_couldnt_e_left: () => { return "OK" },
    _Cant_see_this_Crownstone__header: () => { return "Can't see this Crownstone!" },
    _Cant_see_this_Crownstone__body: () => { return "You have to be in range of Crownstone before " + (arguments[0] ? "enabling" : "disabling") + " Switchcraft." },
    _Cant_see_this_Crownstone__left: () => { return "OK" },
    _Im_sorry_____I_couldnt_c_header: () => { return "I'm sorry..." },
    _Im_sorry_____I_couldnt_c_body: () => { return "I couldn't configure Switchcraft on this Crownstone. Please move closer and try again." },
    _Im_sorry_____I_couldnt_c_left: () => { return "OK" },
    _Cant_see_this_stone___I__header: () => { return "Can't see this stone!" },
    _Cant_see_this_stone___I__body: () => { return "I have to be in range to get the firwmare version of this Crownstone." },
    _Cant_see_this_stone___I__left: () => { return "OK" },
    _Whoops___I_could_not_get_header: () => { return "Whoops!" },
    _Whoops___I_could_not_get_body: () => { return "I could not get the firmware version...." },
    _Whoops___I_could_not_get_left: () => { return "OK" },
    _Whoops___I_could_not_get__header: () => { return "Whoops!" },
    _Whoops___I_could_not_get__body: () => { return "I could not get the hardware version...." },
    _Whoops___I_could_not_get__left: () => { return "OK" },
  },
  DeviceOverview:{
    __filename: "../js/views/deviceViews/DeviceOverview.tsx",
    _Crownstone_is_Locked___Y_header: () => { return "Crownstone is Locked." },
    _Crownstone_is_Locked___Y_body: () => { return "You can edit the behaviour when the Crownstone is unlocked again." },
    _Crownstone_is_Locked___Y_left: () => { return "OK" },
  },
  DeviceSchedule:{
    __filename: "../js/views/deviceViews/elements/DeviceSchedule.tsx",
    _Cant_see_Crownstone___Yo_header: () => { return "Can't see Crownstone!" },
    _Cant_see_Crownstone___Yo_body: () => { return "You cannot sync schedules from Crownstone if I can't see it..." },
    _Cant_see_Crownstone___Yo_left: () => { return "OK" },
    _Could_not_Sync__Move_clo_header: () => { return "Could not Sync" },
    _Could_not_Sync__Move_clo_body: () => { return "Move closer to the Crownstone and try again!" },
    _Could_not_Sync__Move_clo_left: () => { return "OK" },
    _Cant_see_Crownstone___You_header: () => { return "Can't see Crownstone!" },
    _Cant_see_Crownstone___You_body: () => { return "You cannot add schedules without being near to the Crownstone." },
    _Cant_see_Crownstone___You_left: () => { return "OK" },
  },
  DeviceScheduleEdit:{
    __filename: "../js/views/deviceViews/DeviceScheduleEdit.tsx",
    _Permission_Denied___You__header: () => { return "Permission Denied." },
    _Permission_Denied___You__body: () => { return "You do not have permission to delete a scheduled action. Only members and admins of this Sphere are allowed to do that." },
    _Permission_Denied___You__left: () => { return "OK" },
    _Cant_see_Crownstone__You_header: () => { return "Can't see Crownstone" },
    _Cant_see_Crownstone__You_body: () => { return "You cannot remove the schedule without being near to the Crownstone" },
    _Cant_see_Crownstone__You_left: () => { return "OK" },
    _Are_you_sure___Remove_sc_header: () => { return "Are you sure?" },
    _Are_you_sure___Remove_sc_body: () => { return "Remove scheduled action?" },
    _Are_you_sure___Remove_sc_left: () => { return "Cancel" },
    _Are_you_sure___Remove_sc_right: () => { return "Remove" },
    _Are_you_sure___Removing__header: () => { return "Are you sure?" },
    _Are_you_sure___Removing__body: () => { return "Removing a scheduled action will also remove it from the Crownstone. You can disable the action to temporarily stop it." },
    _Are_you_sure___Removing__left: () => { return "Cancel" },
    _Are_you_sure___Removing__right: () => { return "Remove" },
    _Pick_a_day___You_need_to_header: () => { return "Pick a day!" },
    _Pick_a_day___You_need_to_body: () => { return "You need to select at least one day where this action will be scheduled for!" },
    _Pick_a_day___You_need_to_left: () => { return "OK" },
    _Cant_see_Crownstone__You__header: () => { return "Can't see Crownstone" },
    _Cant_see_Crownstone__You__body: () => { return "You cannot change the schedule without being near to the Crownstone." },
    _Cant_see_Crownstone__You__left: () => { return "OK" },
    _Schedules_are_full__argu_header: () => { return "Schedules are full!" },
    _Schedules_are_full__argu_body: () => { return arguments[0] },
    _Schedules_are_full__argu_left: () => { return "No..." },
    _Schedules_are_full__argu_right: () => { return "OK" },
    _Whoops__arguments___No___header: () => { return "Whoops!" },
    _Whoops__arguments___No___body: () => { return arguments[0] },
    _Whoops__arguments___No___left: () => { return "No..." },
    _Whoops__arguments___No___right: () => { return "OK" },
    _Whoops___I_could_not_tel_header: () => { return "Whoops!" },
    _Whoops___I_could_not_tel_body: () => { return "I could not tell this Crownstone to update the Schedule... Would you like to try again? Make sure you\'re in range of the Crownstone! If you press No, your changes will be reverted. " },
    _Whoops___I_could_not_tel_left: () => { return "No..." },
    _Whoops___I_could_not_tel_right: () => { return "OK" },
    _Whoops___I_could_not_tell_header: () => { return "Whoops!" },
    _Whoops___I_could_not_tell_body: () => { return "I could not tell the Crownstone to disable this scheduled action. Would you like to try again? Make sure you're in range of the Crownstone!" },
    _Whoops___I_could_not_tell_left: () => { return "No..." },
    _Whoops___I_could_not_tell_right: () => { return "OK" },
    _Whoops___I_could_not_tell__header: () => { return "Whoops!" },
    _Whoops___I_could_not_tell__body: () => { return "I could not tell the Crownstone to remove this scheduled action. Would you like to try again? Make sure you're in range of the Crownstone!" },
    _Whoops___I_could_not_tell__left: () => { return "No..." },
    _Whoops___I_could_not_tell__right: () => { return "OK" },
  },
  DfuDeviceEntry:{
    __filename: "../js/views/components/deviceEntries/DfuDeviceEntry.tsx",
    _You_dont_have_permission_header: () => { return "You don't have permission." },
    _You_dont_have_permission_body: () => { return "You can ask an admin in your Sphere to update this Crownstone" },
    _You_dont_have_permission_left: () => { return "OK" },
  },
  DfuOverlay:{
    __filename: "../js/views/overlays/DfuOverlay.tsx",
    _Are_you_sure___You_can_a_header: () => { return "Are you sure?" },
    _Are_you_sure___You_can_a_body: () => { return "You can always update this Crownstone later by tapping on it again." },
    _Are_you_sure___You_can_a_left: () => { return "Not yet" },
    _Are_you_sure___You_can_a_right: () => { return "OK" },
    _Are_you_sure___You_can_al_header: () => { return "Are you sure?" },
    _Are_you_sure___You_can_al_body: () => { return "You can always update this Crownstone later." },
    _Are_you_sure___You_can_al_left: () => { return "No" },
    _Are_you_sure___You_can_al_right: () => { return "Yes" },
  },
  LibMessages:{
    __filename: "../js/views/overlays/LibMessages.tsx",
    arguments___arguments___O_header: () => { return arguments[0] },
    arguments___arguments___O_body: () => { return arguments[0] },
    arguments___arguments___O_left: () => { return "OK" },
  },
  LockOverlay:{
    __filename: "../js/views/overlays/LockOverlay.tsx",
    _Im_sorry____Something_we_header: () => { return "I'm sorry.." },
    _Im_sorry____Something_we_body: () => { return "Something went wrong while locking this Crownstone. Make sure you're near the Crownstone that you want to lock." },
    _Im_sorry____Something_we_left: () => { return "OK" },
  },
  Login:{
    __filename: "../js/views/startupViews/Login.tsx",
    _Check_Email_Address__Ple_header: () => { return "Check Email Address" },
    _Check_Email_Address__Ple_body: () => { return "Please input a valid email address in the form and press the Forgot Password button again." },
    _Check_Email_Address__Ple_left: () => { return "OK" },
    _Send_Password_Reset_Emai_header: () => { return "Send Password Reset Email" },
    _Send_Password_Reset_Emai_body: () => { return "Would you like us to send an email to reset your password to: " + arguments[0] + "?" },
    _Send_Password_Reset_Emai_left: () => { return "Cancel" },
    _Send_Password_Reset_Emai_right: () => { return "OK" },
    _Cannot_Send_Email_argume_header: () => { return "Cannot Send Email" },
    _Cannot_Send_Email_argume_body: () => { return arguments[0] },
    _Cannot_Send_Email_argume_left: () => { return "OK" },
    _Your_email_address_has_n_header: () => { return "Your email address has not been verified." },
    _Your_email_address_has_n_body: () => { return "Please click on the link in the email that was sent to you. If you did not receive an email, press Resend Email to try again." },
    _Your_email_address_has_n_left: () => { return "Resend Email" },
    _Your_email_address_has_n_right: () => { return "OK" },
    arguments___arguments___O_header: () => { return arguments[0] },
    arguments___arguments___O_body: () => { return arguments[0] },
    arguments___arguments___O_left: () => { return "OK" },
    _Almost_there___Please_in_header: () => { return "Almost there!" },
    _Almost_there___Please_in_body: () => { return "Please input your email and password." },
    _Almost_there___Please_in_left: () => { return "OK" },
    _Your_email_address_has_no_header: () => { return "Your email address has not been verified" },
    _Your_email_address_has_no_body: () => { return "Please click on the link in the email that was sent to you. If you did not receive an email, press Resend Email to try again." },
    _Your_email_address_has_no_left: () => { return "Resend Email" },
    _Your_email_address_has_no_right: () => { return "OK" },
    _Incorrect_Email_or_Passw_header: () => { return "Incorrect Email or Password." },
    _Incorrect_Email_or_Passw_body: () => { return "Could not log in." },
    _Incorrect_Email_or_Passw_left: () => { return "OK" },
    _Connection_Problem__Coul_header: () => { return "Connection Problem" },
    _Connection_Problem__Coul_body: () => { return "Could not connect to the Cloud. Please check your internet connection." },
    _Connection_Problem__Coul_left: () => { return "OK" },
    _Whoops___An_error_has_oc_header: () => { return "Whoops!" },
    _Whoops___An_error_has_oc_body: () => { return "An error has occurred while syncing with the Cloud. Please try again later." },
    _Whoops___An_error_has_oc_left: () => { return "OK" },
    _DEBUG__err__arguments____header: () => { return "DEBUG: err:" },
    _DEBUG__err__arguments____body: () => { return arguments[0] },
    _DEBUG__err__arguments____left: () => { return "OK" },
  },
  MeshElement:{
    __filename: "../js/views/components/MeshElement.tsx",
    _Update_Required__The_fir_header: () => { return "Update Required" },
    _Update_Required__The_fir_body: () => { return "The firmware of this Crownstone must be updated before it can show connections." },
    _Update_Required__The_fir_left: () => { return "OK" },
  },
  MessageAdd:{
    __filename: "../js/views/messaging/MessageAdd.tsx",
    _Message_is_empty____I_ca_header: () => { return "Message is empty.." },
    _Message_is_empty____I_ca_body: () => { return "I can't send an empty message." },
    _Message_is_empty____I_ca_left: () => { return "Right" },
    _No_recipients____I_cant__header: () => { return "No recipients.." },
    _No_recipients____I_cant__body: () => { return "I can't send a message to nobody." },
    _No_recipients____I_cant__left: () => { return "Right" },
  },
  PictureCircle:{
    __filename: "../js/views/components/PictureCircle.tsx",
    _Delete_this_picture__arg_header: () => { return "Delete this picture?" },
    _Delete_this_picture__arg_body: () => { return arguments[0] },
    _Delete_this_picture__arg_left: () => { return "No" },
    _Delete_this_picture__arg_right: () => { return "Yes" },
    _Sorry_arguments___OKnull_header: () => { return "Sorry" },
    _Sorry_arguments___OKnull_body: () => { return arguments[0] },
    _Sorry_arguments___OKnull_left: () => { return "OK" },
  },
  Register:{
    __filename: "../js/views/startupViews/Register.tsx",
    _Invalid_Email_Address__P_header: () => { return "Invalid Email Address" },
    _Invalid_Email_Address__P_body: () => { return "Please double check the supplied email address." },
    _Invalid_Email_Address__P_left: () => { return "OK" },
    _Check_the_Verification_P_header: () => { return "Check the Verification Password." },
    _Check_the_Verification_P_body: () => { return arguments[0] },
    _Check_the_Verification_P_left: () => { return "OK" },
    _Invalid_Password_argumen_header: () => { return "Invalid Password" },
    _Invalid_Password_argumen_body: () => { return arguments[0] },
    _Invalid_Password_argumen_left: () => { return "OK" },
    _You_Must_Enter_a_First_N_header: () => { return "You Must Enter a First Name." },
    _You_Must_Enter_a_First_N_body: () => { return "Without numbers and at least 2 letters." },
    _You_Must_Enter_a_First_N_left: () => { return "OK" },
    _You_Must_Enter_a_Last_Na_header: () => { return "You Must Enter a Last Name." },
    _You_Must_Enter_a_Last_Na_body: () => { return "Without numbers and at least 2 letters." },
    _You_Must_Enter_a_Last_Na_left: () => { return "OK" },
    _Registration_Error_argum_header: () => { return "Registration Error" },
    _Registration_Error_argum_body: () => { return arguments[0] },
    _Registration_Error_argum_left: () => { return "OK" },
  },
  RoomAdd:{
    __filename: "../js/views/roomViews/RoomAdd.tsx",
    _Room_name_must_be_at_lea_header: () => { return "Room name must be at least 1 character long." },
    _Room_name_must_be_at_lea_body: () => { return "Please change the name and try again." },
    _Room_name_must_be_at_lea_left: () => { return "OK" },
    _Whoops___Something_went__header: () => { return "Whoops!" },
    _Whoops___Something_went__body: () => { return "Something went wrong, please try again later!" },
    _Whoops___Something_went__left: () => { return "OK" },
    _Room_already_exists___Pl_header: () => { return "Room already exists." },
    _Room_already_exists___Pl_body: () => { return "Please change the name and try again." },
    _Room_already_exists___Pl_left: () => { return "OK" },
  },
  RoomEdit:{
    __filename: "../js/views/roomViews/RoomEdit.tsx",
    _Encountered_Cloud_Issue__header: () => { return "Encountered Cloud Issue." },
    _Encountered_Cloud_Issue__body: () => { return "We cannot delete this Room in the Cloud. Please try again later." },
    _Encountered_Cloud_Issue__left: () => { return "OK" },
    _Retrain_Room__Only_do_th_header: () => { return "Retrain Room" },
    _Retrain_Room__Only_do_th_body: () => { return "Only do this if you experience issues with the indoor localization." },
    _Retrain_Room__Only_do_th_left: () => { return "Cancel" },
    _Retrain_Room__Only_do_th_right: () => { return "OK" },
    _Are_you_sure___Removing__header: () => { return "Are you sure?" },
    _Are_you_sure___Removing__body: () => { return "Removing this Room will make all contained Crownstones floating." },
    _Are_you_sure___Removing__left: () => { return "Cancel" },
    _Are_you_sure___Removing__right: () => { return "Remove" },
  },
  RoomOverview:{
    __filename: "../js/views/roomViews/RoomOverview.tsx",
    _Lets_teach_____arguments_header: () => { return "Lets teach " + arguments[0] + " how to identify this room!" },
    _Lets_teach_____arguments_body: () => { return "Tap the flashing icon in the top right corner to go the edit menu and tap the button 'Teach " + arguments[0] + " to find you!'." },
    _Lets_teach_____arguments_left: () => { return "OK" },
    _Youre_not_in_the_Sphere__header: () => { return "You're not in the Sphere" },
    _Youre_not_in_the_Sphere__body: () => { return "Training is only possible if you're in the Sphere. Try again when you are." },
    _Youre_not_in_the_Sphere__left: () => { return "OK" },
  },
  RoomTraining:{
    __filename: "../js/views/roomViews/RoomTraining.tsx",
    _No_Crownstones_in_range__header: () => { return "No Crownstones in range..." },
    _No_Crownstones_in_range__body: () => { return "To be able to identify this room, I need to see at least 3 Crownstones, but I can't see any from here... Try to reposition your Crownstones so I can see more of them." },
    _No_Crownstones_in_range__left: () => { return "OK" },
    _I_can_not_see_enough_Cro_header: () => { return "I can not see enough Crownstones..." },
    _I_can_not_see_enough_Cro_body: () => { return "To be able to identify this room, I need to see at least 3 Crownstones but I see only " + arguments[0] + "." + "Try to reposition your Crownstones so I can see more of them." },
    _I_can_not_see_enough_Cro_left: () => { return "OK" },
    _Do_you_want_to_cancel_tr_header: () => { return "Do you want to cancel training?" },
    _Do_you_want_to_cancel_tr_body: () => { return "Cancelling this process will revert it to the way it was before." },
    _Do_you_want_to_cancel_tr_left: () => { return "No" },
    _Do_you_want_to_cancel_tr_right: () => { return "Yes" },
  },
  SettingConstructor:{
    __filename: "../js/util/SettingConstructor.tsx",
    _Log_out__Are_you_sure__I_header: () => { return "Log out" },
    _Log_out__Are_you_sure__I_body: () => { return "Are you sure? I will tidy up and close the app. Next time you open it you can log in again!" },
    _Log_out__Are_you_sure__I_left: () => { return "Cancel" },
    _Log_out__Are_you_sure__I_right: () => { return "OK" },
  },
  SettingsDeveloper:{
    __filename: "../js/views/settingsViews/SettingsDeveloper.tsx",
    _Clear_all_Logs___Press_O_header: () => { return "Clear all Logs?" },
    _Clear_all_Logs___Press_O_body: () => { return "Press OK to clear logs." },
    _Clear_all_Logs___Press_O_left: () => { return "Cancel" },
    _Clear_all_Logs___Press_O_right: () => { return "OK" },
    _Error_during_sync__argum_header: () => { return "Error during sync." },
    _Error_during_sync__argum_body: () => { return arguments[0] && arguments[1] || arguments[2] },
    _Error_during_sync__argum_left: () => { return "OK" },
    _Sync_already_in_progress_header: () => { return "Sync already in progress." },
    _Sync_already_in_progress_body: () => { return "There already is an active syncing process running in the background. Syncing can take a long time if there are a lot op power measurements that require syncing." },
    _Sync_already_in_progress_left: () => { return "OK" },
    _Notification_Received____header: () => { return "Notification Received!" },
    _Notification_Received____body: () => { return "Everything is working as it should be!" },
    _Notification_Received____left: () => { return "Great!" },
    _Nothing_Received_____May_header: () => { return "Nothing Received..." },
    _Nothing_Received_____May_body: () => { return "Maybe try again?" },
    _Nothing_Received_____May_left: () => { return "OK..." },
    _Could_not_send_Request___header: () => { return "Could not send Request!" },
    _Could_not_send_Request___body: () => { return "There was an error. \n" + arguments[0] },
    _Could_not_send_Request___left: () => { return "Hmm.." },
    _No_device_Id___There_was_header: () => { return "No device Id!" },
    _No_device_Id___There_was_body: () => { return "There was an error." },
    _No_device_Id___There_was_left: () => { return "Hmm.." },
    _Are_you_sure___Only_enab_header: () => { return "Are you sure?" },
    _Are_you_sure___Only_enab_body: () => { return "Only enable this if you know what you're doing!" },
    _Are_you_sure___Only_enab_left: () => { return "Nevermind..." },
    _Are_you_sure___Only_enab_right: () => { return "Do it." },
    _Are_you_sure___This_will_header: () => { return "Are you sure?" },
    _Are_you_sure___This_will_body: () => { return "This will reset all mesh networks in the current Sphere." },
    _Are_you_sure___This_will_left: () => { return "Do it." },
    _Reset_Done__Rediscovery__header: () => { return "Reset Done" },
    _Reset_Done__Rediscovery__body: () => { return "Rediscovery will start automatically." },
    _Reset_Done__Rediscovery__left: () => { return "OK" },
    _EXPERIMENTAL___Switchcra_header: () => { return "EXPERIMENTAL!" },
    _EXPERIMENTAL___Switchcra_body: () => { return "Switchcraft is currently in the experimental phase. It will not detect all switches, " + "it might switch accidentally or your Built-in Crownstone might be unsupported.\n\n" + "Use this at your own risk! Are you sure?" },
    _EXPERIMENTAL___Switchcra_left: () => { return "I'll wait." },
    _EXPERIMENTAL___Switchcra_right: () => { return "Yes." },
  },
  SettingsFactoryResetStep2:{
    __filename: "../js/views/settingsViews/SettingsFactoryResetStep2.tsx",
    _Crownstone_in_Setup_mode_header: () => { return "Crownstone in Setup mode nearby." },
    _Crownstone_in_Setup_mode_body: () => { return "We detect a Crownstone in setup mode close by, as well as one in normal mode which is already in your Sphere (" + arguments[0] + "). Do you want to try to factory reset your own Crownstone?" },
    _Crownstone_in_Setup_mode_left: () => { return "Cancel" },
    _Crownstone_in_Setup_mode_right: () => { return "Recover" },
    _Crownstone_in_Setup_mode__header: () => { return "Crownstone in Setup mode nearby." },
    _Crownstone_in_Setup_mode__body: () => { return "We detect a Crownstone in setup mode close by, as well as one in normal mode which is already in your Sphere and a bit farther away (" + arguments[0] + "). If you want to try to factory reset this one, move closer to it." },
    _Crownstone_in_Setup_mode__left: () => { return "OK" },
    _Crownstone_in_Setup_mode_n_header: () => { return "Crownstone in Setup mode nearby." },
    _Crownstone_in_Setup_mode_n_body: () => { return "We detect a Crownstone in setup mode close by, as well as one in normal mode that is not in your Spheres. Do you still want to try to factory reset the one in normal mode?" },
    _Crownstone_in_Setup_mode_n_left: () => { return "Cancel" },
    _Crownstone_in_Setup_mode__right: () => { return "Recover" },
    _Crownstone_in_Setup_mode_ne_header: () => { return "Crownstone in Setup mode nearby." },
    _Crownstone_in_Setup_mode_ne_body: () => { return "We detect a Crownstone in setup mode close by, and one in normal mode (that is not in your Spheres) a bit further away. Do you still want to try to factory reset the one in normal mode?" },
    _Crownstone_in_Setup_mode_ne_left: () => { return "Cancel" },
    _Crownstone_in_Setup_mode_n_right: () => { return "Recover" },
    _No_unknown_Crownstone_ne_header: () => { return "No unknown Crownstone nearby." },
    _No_unknown_Crownstone_ne_body: () => { return "We detect a Crownstone that is already in your Sphere (" + arguments[0] + "). Do you want to try to factory reset your own Crownstone?" },
    _No_unknown_Crownstone_ne_left: () => { return "Cancel" },
    _No_unknown_Crownstone_ne_right: () => { return "Recover" },
    _No_unknown_Crownstones_f_header: () => { return "No unknown Crownstones found." },
    _No_unknown_Crownstones_f_body: () => { return "We detect a Crownstone that is already in your Sphere (" + arguments[0] + ") and not very close. If you want to try to factory reset this one, move closer to it." },
    _No_unknown_Crownstones_f_left: () => { return "OK" },
    _No_Crownstones_near___We_header: () => { return "No Crownstones near." },
    _No_Crownstones_near___We_body: () => { return "We detect a Crownstone but it's not very close by. Please move closer and try again. If you are already holding your phone very close to the Crownstone something may be wrong." },
    _No_Crownstones_near___We_left: () => { return "OK" },
    _Recovery_might_not_be_ne_header: () => { return "Recovery might not be needed." },
    _Recovery_might_not_be_ne_body: () => { return "We can not find a suitable Crownstone in range, though there is a Crownstone in setup mode close by. Maybe the Crownstone has already been set to factory defaults? Try adding it to your Sphere!" },
    _Recovery_might_not_be_ne_left: () => { return "OK" },
    _No_nearby_Crownstones____header: () => { return "No nearby Crownstones." },
    _No_nearby_Crownstones____body: () => { return "We can't find any Crownstones nearby, please follow the steps again to retry. Make sure to hold your phone close!" },
    _No_nearby_Crownstones____left: () => { return "OK" },
    _Success___This_Crownston_header: () => { return "Success!" },
    _Success___This_Crownston_body: () => { return "This Crownstone has been reset to factory defaults. After plugging it in and out once more, you can add it to a new Sphere." },
    _Success___This_Crownston_left: () => { return "OK" },
    _Not_in_Factory_Reset_mod_header: () => { return "Not in Factory Reset mode." },
    _Not_in_Factory_Reset_mod_body: () => { return "You have 20 seconds after you plug the Crownstone in to factory reset it. Please follow the steps again to retry." },
    _Not_in_Factory_Reset_mod_left: () => { return "OK" },
    _Error_during_Factory_Res_header: () => { return "Error during Factory Reset." },
    _Error_during_Factory_Res_body: () => { return "Please repeat the process to try again." },
    _Error_during_Factory_Res_left: () => { return "OK" },
  },
  SettingsMeshDebug:{
    __filename: "../js/views/settingsViews/dev/SettingsMeshDebug.tsx",
    _All_done___This_went_ver_header: () => { return "All done!" },
    _All_done___This_went_ver_body: () => { return "This went very well!" },
    _All_done___This_went_ver_left: () => { return "Nice." },
    _Missed_one__I_could_not__header: () => { return "Missed one" },
    _Missed_one__I_could_not__body: () => { return "I could not change " + arguments[0] },
    _Missed_one__I_could_not__left: () => { return "OK" },
  },
  SettingsMeshTopology:{
    __filename: "../js/views/settingsViews/SettingsMeshTopology.tsx",
    _Refresh_Topology__While__header: () => { return "Refresh Topology" },
    _Refresh_Topology__While__body: () => { return "While the topology updates automatically, if you move a Crownstone out of range of the others " + "it will take a while for the connection to time out. Manually refreshing like this will speed up this process." },
    _Refresh_Topology__While__left: () => { return "Cancel" },
    _Refresh_Topology__While__right: () => { return "OK" },
  },
  SettingsPrivacy:{
    __filename: "../js/views/settingsViews/SettingsPrivacy.tsx",
    _Phone_Details_Removed__W_header: () => { return "Phone Details Removed" },
    _Phone_Details_Removed__W_body: () => { return "We have removed your phone details from the Cloud." },
    _Phone_Details_Removed__W_left: () => { return "OK" },
    _Whoops___We_could_not_re_header: () => { return "Whoops!" },
    _Whoops___We_could_not_re_body: () => { return "We could not remove your phone details from the Cloud. Please try again later." },
    _Whoops___We_could_not_re_left: () => { return "OK" },
  },
  SettingsProfile:{
    __filename: "../js/views/settingsViews/SettingsProfile.tsx",
    _First_name_must_be_at_le_header: () => { return "First name must be at least 1 letter long" },
    _First_name_must_be_at_le_body: () => { return "No numbers allowed either." },
    _First_name_must_be_at_le_left: () => { return "OK" },
    _Last_name_must_be_at_lea_header: () => { return "Last name must be at least 1 letter long" },
    _Last_name_must_be_at_lea_body: () => { return "No numbers allowed either." },
    _Last_name_must_be_at_lea_left: () => { return "OK" },
    _Are_you_sure_you_want_to_header: () => { return "Are you sure you want to reset your password?" },
    _Are_you_sure_you_want_to_body: () => { return "You will receive a password reset email with instructions at \'" + arguments[0] + "\'. You will be logged out when the email has been sent." },
    _Are_you_sure_you_want_to_left: () => { return "Cancel" },
    _Are_you_sure_you_want_to_right: () => { return "OK" },
    _Reset_email_has_been_sen_header: () => { return "Reset email has been sent" },
    _Reset_email_has_been_sen_body: () => { return "You will now be logged out. Follow the instructions in the email and log in with your new password." },
    _Reset_email_has_been_sen_left: () => { return "OK" },
    _Cannot_Send_Email_argume_header: () => { return "Cannot Send Email" },
    _Cannot_Send_Email_argume_body: () => { return arguments[0] },
    _Cannot_Send_Email_argume_left: () => { return "OK" },
  },
  SetupDeviceEntry:{
    __filename: "../js/views/components/deviceEntries/SetupDeviceEntry.tsx",
    _You_dont_have_permission_header: () => { return "You don't have permission" },
    _You_dont_have_permission_body: () => { return "You can ask an admin in your Sphere to setup this Crownstone" },
    _You_dont_have_permission_left: () => { return "OK" },
  },
  SideBar:{
    __filename: "../js/views/components/sideMenu/SideBar.tsx",
    _Are_you_sure___Crownston_header: () => { return "Are you sure?" },
    _Are_you_sure___Crownston_body: () => { return "Crownstones will not respond to you if you force quit the app. It will not run in the background anymore either." },
    _Are_you_sure___Crownston_left: () => { return "Cancel" },
    _Are_you_sure___Crownston_right: () => { return "OK" },
  },
  SphereCrownstoneOverview:{
    __filename: "../js/views/main/editSubviews/SphereCrownstoneOverview.tsx",
    _Ask_your_Sphere_Admin__A_header: () => { return "Ask your Sphere Admin" },
    _Ask_your_Sphere_Admin__A_body: () => { return "Admins can add new Crownstones to Spheres. If you have a new Crownstone you'd like to add, ask the sphere Admin." },
    _Ask_your_Sphere_Admin__A_left: () => { return "OK" },
  },
  SphereEditSettings:{
    __filename: "../js/views/main/editSubviews/SphereEditSettings.tsx",
    _Sphere_name_must_be_at_l_header: () => { return "Sphere name must be at least 2 letters long" },
    _Sphere_name_must_be_at_l_body: () => { return "Please try again." },
    _Sphere_name_must_be_at_l_left: () => { return "OK" },
    _Are_you_sure_you_want_to_header: () => { return "Are you sure you want to leave this Sphere?" },
    _Are_you_sure_you_want_to_body: () => { return "If you are the Sphere owner, you will have to transfer ownership first." },
    _Are_you_sure_you_want_to_left: () => { return "No" },
    _Are_you_sure_you_want_to_right: () => { return "Yes" },
    _Are_you_sure_you_want_to__header: () => { return "Are you sure you want to delete this Sphere?" },
    _Are_you_sure_you_want_to__body: () => { return "This is only possible if you have removed all Crownstones from this Sphere." },
    _Are_you_sure_you_want_to__left: () => { return "No" },
    _Are_you_sure_you_want_to__right: () => { return "Yes" },
    _Could_not_delete_Sphere__header: () => { return "Could not delete Sphere!" },
    _Could_not_delete_Sphere__body: () => { return "Please try again later." },
    _Could_not_delete_Sphere__left: () => { return "OK" },
  },
  SphereIntegrations:{
    __filename: "../js/views/main/editSubviews/SphereIntegrations.tsx",
    _Working_on_it___Support__header: () => { return "Working on it!" },
    _Working_on_it___Support__body: () => { return "Support for Philips Hue will be added in a future update." },
    _Working_on_it___Support__left: () => { return "OK" },
  },
  SphereInvitedUser:{
    __filename: "../js/views/main/editSubviews/SphereInvitedUser.tsx",
    _Lets_remind_someone___Wo_header: () => { return "Let's remind someone!" },
    _Lets_remind_someone___Wo_body: () => { return "Would you like me to send another invitation email?." },
    _Lets_remind_someone___Wo_left: () => { return "No" },
    _Lets_remind_someone___Wo_right: () => { return "Yes" },
    _Could_not_resend_email___header: () => { return "Could not resend email.." },
    _Could_not_resend_email___body: () => { return "Please try again later." },
    _Could_not_resend_email___left: () => { return "OK" },
    _Are_you_sure___Shall_I_r_header: () => { return "Are you sure?" },
    _Are_you_sure___Shall_I_r_body: () => { return "Shall I revoke the invitation?" },
    _Are_you_sure___Shall_I_r_left: () => { return "No" },
    _Are_you_sure___Shall_I_r_right: () => { return "Yes" },
    _Could_not_revoke_invitat_header: () => { return "Could not revoke invitation.." },
    _Could_not_revoke_invitat_body: () => { return "Please try again later." },
    _Could_not_revoke_invitat_left: () => { return "OK" },
  },
  SphereUser:{
    __filename: "../js/views/main/editSubviews/SphereUser.tsx",
    _Something_went_wrong__Pl_header: () => { return "Something went wrong" },
    _Something_went_wrong__Pl_body: () => { return "Please try again later." },
    _Something_went_wrong__Pl_left: () => { return "OK" },
    _Are_you_sure_you_want_to_header: () => { return "Are you sure you want to remove this user from the sphere?" },
    _Are_you_sure_you_want_to_body: () => { return "User's permissions will be revoked the next time he/she logs into the app." },
    _Are_you_sure_you_want_to_left: () => { return "No" },
    _Are_you_sure_you_want_to_right: () => { return "Yes" },
    _Something_went_wrong__Ple_header: () => { return "Something went wrong" },
    _Something_went_wrong__Ple_body: () => { return "Please try again later." },
    _Something_went_wrong__Ple_left: () => { return "OK" },
  },
  SphereUserInvite:{
    __filename: "../js/views/main/editSubviews/SphereUserInvite.tsx",
    _Please_provide_an_email__header: () => { return "Please provide an email address" },
    _Please_provide_an_email__body: () => { return "" },
    _Please_provide_an_email__left: () => { return "OK" },
    _Please_provide_a_valid_e_header: () => { return "Please provide a valid email address" },
    _Please_provide_a_valid_e_body: () => { return "" },
    _Please_provide_a_valid_e_left: () => { return "OK" },
    _User_already_in_Sphere___header: () => { return "User already in Sphere" },
    _User_already_in_Sphere___body: () => { return "A user with this email address is already in the Sphere." },
    _User_already_in_Sphere___left: () => { return "OK" },
    _Invite_has_been_sent___A_header: () => { return "Invite has been sent!" },
    _Invite_has_been_sent___A_body: () => { return "An email has been sent to " + arguments[0] + "." },
    _Invite_has_been_sent___A_left: () => { return "OK" },
    _Could_not_send_invite____header: () => { return "Could not send invite.." },
    _Could_not_send_invite____body: () => { return "Please try again later." },
    _Could_not_send_invite____left: () => { return "OK" },
  },
  TapToToggleCalibration:{
    __filename: "../js/views/overlays/TapToToggleCalibration.tsx",
    _Thats_a_bit_far_away___M_header: () => { return "That's a bit far away." },
    _Thats_a_bit_far_away___M_body: () => { return "Maybe try again later." },
    _Thats_a_bit_far_away___M_left: () => { return "OK" },
    _Thats_a_bit_far_away___T_header: () => { return "That's a bit far away." },
    _Thats_a_bit_far_away___T_body: () => { return "Try to hold your phone really close to a Crownstone and press OK to retry!" },
    _Thats_a_bit_far_away___T_left: () => { return "OK" },
    _Something_went_wrong__Ma_header: () => { return "Something went wrong" },
    _Something_went_wrong__Ma_body: () => { return "Maybe try again later." },
    _Something_went_wrong__Ma_left: () => { return "OK" },
    _Training_Tap_to_Toggle_L_header: () => { return "Training Tap-to-Toggle Later" },
    _Training_Tap_to_Toggle_L_body: () => { return arguments[0] },
    _Training_Tap_to_Toggle_L_left: () => { return "OK" },
  },
  ToonAdd:{
    __filename: "../js/views/thirdParty/toon/ToonAdd.tsx",
    _No_Toon_Found__This_acco_header: () => { return "No Toon Found" },
    _No_Toon_Found__This_acco_body: () => { return "This account does not seem to have a Toon we can use...." },
    _No_Toon_Found__This_acco_left: () => { return "OK" },
    _Whoops__The_provided_cod_header: () => { return "Whoops" },
    _Whoops__The_provided_cod_body: () => { return "The provided code seems to be incorrect." },
    _Whoops__The_provided_cod_left: () => { return "OK" },
    _Whoops__Something_went_w_header: () => { return "Whoops" },
    _Whoops__Something_went_w_body: () => { return "Something went wrong... Please try again later." },
    _Whoops__Something_went_w_left: () => { return "OK" },
  },
  ToonOverview:{
    __filename: "../js/views/thirdParty/toon/ToonOverview.tsx",
    _Are_you_sure__You_will_h_header: () => { return "Are you sure" },
    _Are_you_sure__You_will_h_body: () => { return "You will have to add Toon again to undo this." },
    _Are_you_sure__You_will_h_left: () => { return "Cancel" },
    _Are_you_sure__You_will_h_right: () => { return "Yes" },
  },
  ToonSettings:{
    __filename: "../js/views/thirdParty/toon/ToonSettings.tsx",
    _Whoops__Something_went_w_header: () => { return "Whoops" },
    _Whoops__Something_went_w_body: () => { return "Something went wrong..." },
    _Whoops__Something_went_w_left: () => { return "OK" },
    _Are_you_sure__You_will_h_header: () => { return "Are you sure" },
    _Are_you_sure__You_will_h_body: () => { return "You will have to add Toon again to undo this." },
    _Are_you_sure__You_will_h_left: () => { return "Cancel" },
    _Are_you_sure__You_will_h_right: () => { return "Yes" },
  },
}