
const ACTIONS = {
  TURN_ON: "TURN_ON",
  REACT_TO_TURN_ON: "REACT_TO_TURN_ON"
}

const CONDITIONS = {
  TIME: "TIME",
  PRESENCE: "PRESENCE",
  NOT_PRESENCE: "NOT_PRESENCE",
  ALWAYS: "ALWAYS",
}

const OFFSET_TYPES = {
  RANDOM:"RANDOM",
  BEFORE:"BEFORE",
  AFTER:"AFTER",
}

const TIME_TYPES = {
  SUNRISE: "SUNRISE",
  SUNSET: "SUNSET",
  MIDNIGHT: "MIDNIGHT",
  NOON: "NOON",
  SPECIFIC: "SPECIFIC",
}

const PRESENCE_TYPES = {
  ANYBODY: "ANYBODY",
  NOBODY: "NOBODY",
  SPECIFIC_USERS: "SPECIFIC_USERS"
}

export {
  ACTIONS,
  CONDITIONS,
  OFFSET_TYPES,
  TIME_TYPES,
  PRESENCE_TYPES
}